Closes #108 | Add Shopee Reviews Tagalog dataloader
SEACrowd/seacrowd-datahub pull request #121
Opened 2023-11-23 07:21 UTC by ljvmiranda921

Closes #108

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2023-11-27 02:55 UTC, yongzx commented
Tested successfully via test script and `datasets.load_dataset()`.

2023-11-29 12:50 UTC, jamesjaya requested changes
reviewed and tested. I have some nits but apart from that, looks good.

2023-11-29 12:50 UTC, jamesjaya commented on seacrowd/sea_datasets/shopee_reviews_tagalog/shopee_reviews_tagalog.py
> +    LABEL_CLASSES = ["0", "1", "2", "3", "4"]
nit I think the labeling may not be very obvious, I would suggest to put an explanation (or maybe just make the label more verbose like "1 star", "2 stars").
```suggestion
    # "N" means N+1 star(s) review, e.g. "2" means 3 stars review
    LABEL_CLASSES = ["0", "1", "2", "3", "4"]
```

2023-11-29 23:36 UTC, ljvmiranda921 commented
Updated! Thank you @yongzx and @jamesjaya :)

2023-11-30 14:15 UTC, merged