Closes #96 | Create dataset loader for LimeSoda
SEACrowd/seacrowd-datahub pull request #154
Opened 2023-12-03 07:48 UTC by jen-santoso

Please name your PR after the issue it closes. You can use the following line: "Closes #96 " where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2023-12-09 14:15 UTC, ljvmiranda921 reviewed
The dataloader runs as expected, but I have some comments on the source code. Also, the default test errors out. Maybe it's better to rename `limesoda_raw_source` into `limesoda_source`? (and `limesoda_raw_seacrowd_text` as `limesoda_seacrowd_text`). Thoughts @sabilmakbar ?

2023-12-09 14:15 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +                    # Whatever you put in gen_kwargs will be passed to _generate_examples
```suggestion
```

2023-12-09 14:15 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +        f.close()
`f.close()`should be unnecessary when you're using the `with` context manager

2023-12-09 14:15 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +        # For example seacrowd_kb, seacrowd_t2t
```suggestion
```

2023-12-09 14:15 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +
Running `make check_file` requires us to delete this extra newline.

```suggestion
```

2023-12-09 14:15 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +                    # Whatever you put in gen_kwargs will be passed to _generate_examples
```suggestion
```

2023-12-09 14:15 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +            df = [json.loads(line) for line in f.readlines()]
I suggest changing the variable name `df` into something more informative. I usually see this in the context of a pandas DataFrame, but I don't see any use of that library here.

2023-12-10 06:25 UTC, jen-santoso commented
> The dataloader runs as expected, but I have some comments on the source code. Also, the default test errors out. Maybe it's better to rename `limesoda_raw_source` into `limesoda_source`? (and `limesoda_raw_seacrowd_text` as `limesoda_seacrowd_text`). Thoughts @sabilmakbar ?

@ljvmiranda921 Thank you for the comments. I was thinking to split the dataset into signify the one with splits and not, therefore naming the splits into `limesoda_raw_source` and `limesoda_split_source`. But think I agree with you with changing `limesoda_raw_source` to `limesoda_source`, it keeps the default runnable and it can still be easily differentiated with the splitted one.
Fixed this, and also the other comments. Please check.

2023-12-10 16:51 UTC, sabilmakbar commented
> The dataloader runs as expected, but I have some comments on the source code. Also, the default test errors out. Maybe it's better to rename limesoda_raw_source into limesoda_source? (and limesoda_raw_seacrowd_text as limesoda_seacrowd_text). Thoughts @sabilmakbar ?

Hi LJ @ljvmiranda921, actually for several cases, it's okay not to implement the default config of `f"{DATASET_NAME}_source"` and its SEACrowd counterpart, as long as it's justified (belongs to either Multilingual, or have different labels per config and/or has each annotator data provided; for manually curated data -- CebuaNER was one of that case). But esp for the second case, if we can be assured of one default implementation among different configs, it can be defined on `f"{DATASET_NAME}_source"`, which I agree on the fix by @jen-santoso based on ur suggestion.

> @ljvmiranda921 Thank you for the comments. I was thinking to split the dataset into signify the one with splits and not, therefore naming the splits into limesoda_raw_source and limesoda_split_source. But think I agree with you with changing limesoda_raw_source to limesoda_source, it keeps the default runnable and it can still be easily differentiated with the splitted one.
Fixed this, and also the other comments. Please check.

Ack, will verify the dataloader & its metadata in the next 24hrs. But before that, do you mind re-running your dataloader w/ this [Code Formatter Check](https://github.com/SEACrowd/seacrowd-datahub/blob/master/DATALOADER.md#5-format-your-code), if possible? I saw some lines aren't coherently formatted; I suspect the code hasn't been linted using SEACrowd Code Formatter.

2023-12-10 22:57 UTC, ljvmiranda921 commented
^Ah thanks for that reminder! I'll be more lenient on the the `_source` implementations next time.

2023-12-10 23:40 UTC, ljvmiranda921 approved these changes
LGTM! Let's just wait for @sabilmakbar 's comments

2023-12-12 07:06 UTC, jen-santoso commented
> 
> Ack, will verify the dataloader & its metadata in the next 24hrs. But before that, do you mind re-running your dataloader w/ this [Code Formatter Check](https://github.com/SEACrowd/seacrowd-datahub/blob/master/DATALOADER.md#5-format-your-code), if possible? I saw some lines aren't coherently formatted; I suspect the code hasn't been linted using SEACrowd Code Formatter.

![image](https://github.com/SEACrowd/seacrowd-datahub/assets/62987563/b308dd9d-40d3-4109-a85e-21041c52b014)
make check_file=seacrowd/sea_datasets/limesoda/limesoda.py result from the latest commit

2023-12-13 18:51 UTC, sabilmakbar requested changes
Two more nits, then all good!

2023-12-13 19:09 UTC, sabilmakbar commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +    DEFAULT_CONFIG_NAME = "limesoda_source"
let's use `_DATASETNAME` variable
```suggestion
            name=f"{_DATASETNAME}_source",
            version=SOURCE_VERSION,
            description="limesoda source schema",
            schema="source",
            subset_id=_DATASETNAME,
        ),
        SEACrowdConfig(
            name=f"{_DATASETNAME}_split_source",
            version=SOURCE_VERSION,
            description="limesoda source schema",
            schema="source",
            subset_id=f"{_DATASETNAME}_split",
        ),
        SEACrowdConfig(
            name=f"{_DATASETNAME}_seacrowd_text",
            version=SEACROWD_VERSION,
            description="limesoda SEACrowd schema",
            schema="seacrowd_text",
            subset_id=_DATASETNAME,
        ),
        SEACrowdConfig(
            name=f"{_DATASETNAME}_split_seacrowd_text",
            version=SEACROWD_VERSION,
            description="limesoda: split SEACrowd schema",
            schema="seacrowd_text",
            subset_id=f"{_DATASETNAME}_split",
        ),
    ]

    DEFAULT_CONFIG_NAME = f"{_DATASETNAME}_source"
```

2023-12-19 06:55 UTC, jen-santoso commented
Ok, I've updated the nits suggested. Also, I added the `_LANGUAGES` constant as well to ensure consistency as recommended in https://github.com/SEACrowd/seacrowd-datahub/pull/72

2023-12-19 10:35 UTC, jen-santoso commented
sorry I missed the class name case nits, fixed now.

2023-12-19 10:50 UTC, sabilmakbar reviewed
add `_LOCAL` variable to indicate whether this dataset needs to have indirect download or free to be downloaded w/o any gate (HF allows the dataset owner to collect user info prior to accessing dataset, which called Free upon Request dataset or Gated Dataset)

2023-12-19 10:50 UTC, sabilmakbar commented on seacrowd/sea_datasets/limesoda/limesoda.py
> +
can you add constant `_LOCAL = False`? it indicates this dataloader doesn't need an indirect download (which can't be catered by HF `DownloadManager` methods).
```suggestion
_LANGUAGES = ["tha"]
_LOCAL = False

```

2023-12-20 15:51 UTC, sabilmakbar approved these changes
LGTM! Thanks @jen-santoso for implementing this dataloader and @ljvmiranda921 for reviewing this!

2023-12-20 15:52 UTC, merged