Add bhinneka_korpus dataset loader
SEACrowd/seacrowd-datahub pull request #175
Opened 2023-12-10 12:29 UTC by joanitolopo

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2023-12-14 07:53 UTC, sabilmakbar commented
Hi @joanitolopo, for visibility, I'm revising the PR init message as follows:

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

to

Closes #9.

Also, I'm adding text `Closes #9 | ` in front of PR Title

2023-12-20 15:00 UTC, jamesjaya commented on seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py
> +                    "text_1_name": process_list(languages),
Please create one example per language instead of doing lists as supplying list here does not conform to the t2t schema

2023-12-20 15:02 UTC, jamesjaya commented on seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py
> +    )
I don't think we need all and per-language datasets, just implement either just per-language or just all.

2023-12-20 15:03 UTC, jamesjaya commented on seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py
> +def process_list(data):
please give the function proper typings if you decide to keep this, but generally I think we don't want a function which can return either a list or a string.

2024-01-05 03:20 UTC, jamesjaya commented on seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py
> +"""
@SamuelCahyawijaya what's your take on this?

2024-01-12 04:47 UTC, joanitolopo commented on seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py
> +class BhinnekaKorpus(datasets.GeneratorBasedBuilder):
i already apply the suggested changes.

2024-01-21 08:16 UTC, jen-santoso requested changes
Hello, thanks for implementing the dataset. 
Here is the initial review, please check and consider the changes.

2024-01-21 23:45 UTC, joanitolopo commented on seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py
> +    dataset_names = sorted([f"bhinneka_korpus_{lang}" for lang in _LANGUAGES])
I already update new changed. Thanks

2024-01-31 05:41 UTC, jen-santoso approved these changes

2024-02-14 05:18 UTC, holylovenia commented
Hi @joanitolopo, may I know if you have addressed @jamesjaya's suggestions? If yes, I'm considering to merge this PR without @jamesjaya's approval because it has been in the backlog for quite some time.

cc: @jen-santoso

2024-02-14 05:47 UTC, jen-santoso commented
@holylovenia @joanitolopo, so I guess it's okay to merge, then? All changes seem to be approved, and all tested OK

2024-02-14 05:50 UTC, holylovenia commented
Yeah agree, @jen-santoso @joanitolopo. Noted! Merging now. 🙏 Thanks for your hardwork!!

2024-02-14 05:50 UTC, merged