Closes #111  | Add Thai Constitution
SEACrowd/seacrowd-datahub pull request #186
Opened 2023-12-17 00:40 UTC by ilhamfp

Closes #111 

Test passed:
<img width="995" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/31740013/d6879a2c-3316-4400-99be-46a20d03dcb9">

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-11 05:30 UTC, holylovenia requested changes
Thanks for the dataloader, @ilhamfp! It's good as usual. 👍 One nit, could you please change `_SUPPORTED_LANGS` to `_LANGUAGES`?

2024-01-12 07:19 UTC, yongzx requested changes

2024-01-12 07:19 UTC, yongzx commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +    def _generate_examples(self, filepaths: list[Path]) -> Tuple[int, Dict]:
it should be `List` instead of `list`.

2024-01-12 07:21 UTC, ilhamfp commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +    def _generate_examples(self, filepaths: list[Path]) -> Tuple[int, Dict]:
Good catch! Updated

2024-01-12 07:26 UTC, yongzx commented
Thanks for the quick fix! One last thing, can you replace `ssp` with `SEACROWD_SCHEMA_NAME` instead? 

See https://github.com/SEACrowd/seacrowd-datahub/pull/153#discussion_r1445956869

2024-01-12 07:27 UTC, yongzx commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +            name="thai_constitution_seacrowd_ssp",
Would be great to replace `ssp` with `self.SEACROWD_SCHEMA_NAME`

2024-01-12 07:27 UTC, yongzx commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +
define `SEACROWD_SCHEMA_NAME = 'ssp'`

2024-01-12 07:27 UTC, yongzx commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +            schema="seacrowd_ssp",
replace `ssp` with `self.SEACROWD_SCHEMA_NAME`

2024-01-12 07:27 UTC, yongzx commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +        elif self.config.schema == "seacrowd_ssp":
replace `ssp` with `self.SEACROWD_SCHEMA_NAME`

2024-01-12 07:27 UTC, yongzx commented on seacrowd/sea_datasets/thai_constitution/thai_constitution.py
> +                    elif self.config.schema == "seacrowd_ssp":
replace `ssp` with `self.SEACROWD_SCHEMA_NAME`

2024-01-16 04:42 UTC, holylovenia approved these changes
Thanks, LGTM! After @ilhamfp addresses @yongzx's feedback, we can merge this.

2024-01-16 10:33 UTC, ilhamfp commented
Updated 👍

2024-01-18 13:57 UTC, yongzx approved these changes

2024-01-18 13:57 UTC, merged