Closes #71 | Create dataset loader for MASSIVE
SEACrowd/seacrowd-datahub pull request #196
Opened 2023-12-21 16:33 UTC by yana-xuyan

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-03 02:50 UTC, gentaiscool requested changes
I was wondering if we should split the slot filling and intent detection dataset. tag @holylovenia @SamuelCahyawijaya @sabilmakbar

2024-01-03 02:50 UTC, gentaiscool commented on seacrowd/sea_datasets/massive/massive.py
> +class MASSIVE(datasets.GeneratorBasedBuilder):
can you modify the class name to MASSIVEDataset for consistency to other datasets?

2024-01-03 02:50 UTC, gentaiscool commented on seacrowd/sea_datasets/massive/massive.py
> +    def _getBioFormat(self, text):
refactor the function name with snake case.

2024-01-04 00:55 UTC, yana-xuyan commented
Hi Genta, sure. For separating the slot filling anc intent detection dataset, I can modify if needed. :)

Best regards,
Yan

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Genta Indra Winata ***@***.***>
发送时间: Wednesday, January 3, 2024 10:50:26 AM
收件人: SEACrowd/seacrowd-datahub ***@***.***>
抄送: Yan XU ***@***.***>; Author ***@***.***>
主题: Re: [SEACrowd/seacrowd-datahub] Closes #71 | Create dataset loader for MASSIVE (PR #196)


@gentaiscool requested changes on this pull request.

I was wondering if we should split the slot filling and intent detection dataset. tag @holylovenia<https://github.com/holylovenia> @SamuelCahyawijaya<https://github.com/SamuelCahyawijaya> @sabilmakbar<https://github.com/sabilmakbar>

________________________________

In seacrowd/sea_datasets/massive/massive.py<https://github.com/SEACrowd/seacrowd-datahub/pull/196#discussion_r1440017954>:

> +    'I-coffee_type', 'B-transport_agency', 'B-podcast_descriptor', 'I-playlist_name', 'B-media_type', 'B-song_name', 'I-music_descriptor',
+    'I-song_name', 'B-event_name', 'I-timeofday', 'B-alarm_type', 'B-cooking_type', 'I-business_name', 'I-color_type', 'B-podcast_name',
+    'I-personal_info', 'B-weather_descriptor', 'I-list_name', 'B-transport_descriptor', 'I-game_type', 'I-date', 'B-place_name', 'B-color_type',
+    'B-game_name', 'I-artist_name', 'I-drink_type', 'B-business_name', 'B-timeofday', 'B-sport_type', 'I-player_setting', 'I-transport_agency',
+    'B-game_type', 'B-player_setting', 'I-music_album', 'I-event_name', 'I-general_frequency', 'I-podcast_name', 'I-cooking_type', 'I-radio_name',
+    'I-joke_type', 'I-meal_type', 'I-transport_type', 'B-joke_type', 'B-time', 'B-order_type', 'B-business_type', 'B-general_frequency',
+    'I-food_type', 'I-time_zone', 'B-currency_name', 'B-time_zone', 'B-ingredient', 'B-house_place', 'B-audiobook_name', 'I-ingredient',
+    'I-media_type', 'I-news_topic', 'B-music_genre', 'I-definition_word', 'B-list_name', 'B-playlist_name', 'B-email_address', 'I-currency_name',
+    'I-movie_name', 'I-device_type', 'I-weather_descriptor', 'B-audiobook_author', 'I-audiobook_author', 'I-app_name', 'I-order_type',
+    'I-transport_name', 'B-radio_name', 'I-business_type', 'B-definition_word', 'B-artist_name', 'I-movie_type', 'B-transport_name', 'I-email_folder',
+    'B-music_album', 'I-house_place', 'I-music_genre', 'B-drink_type', 'I-alarm_type', 'B-music_descriptor', 'B-news_topic', 'B-meal_type',
+    'I-transport_descriptor', 'I-email_address', 'I-change_amount', 'B-device_type', 'B-transport_type', 'B-relation', 'I-sport_type', 'B-personal_info'
+]
+
+
+class MASSIVE(datasets.GeneratorBasedBuilder):


can you modify the class name to MASSIVEDataset for consistency to other datasets?

________________________________

In seacrowd/sea_datasets/massive/massive.py<https://github.com/SEACrowd/seacrowd-datahub/pull/196#discussion_r1440018120>:

> +                    "split": "dev",
+                    "lang": self.config.name,
+                }
+            ),
+            datasets.SplitGenerator(
+                name=datasets.Split.TEST,
+                gen_kwargs={
+                    "files": dl_manager.iter_archive(archive),
+                    "split": "test",
+                    "lang": self.config.name,
+                }
+            ),
+        ]
+
+
+    def _getBioFormat(self, text):


refactor the function name with snake case.

―
Reply to this email directly, view it on GitHub<https://github.com/SEACrowd/seacrowd-datahub/pull/196#pullrequestreview-1801302130>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJGALO2AKRJMSTNFSJBWGL3YMTBPFAVCNFSM6AAAAABA6U57AOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMBRGMYDEMJTGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-01-06 07:32 UTC, yana-xuyan commented
Hi @gentaiscool, I have modified the code accordingly. Do you think we need to split the slot filling and intent detection dataset btw?

2024-01-08 04:31 UTC, holylovenia commented
> Hi @gentaiscool, I have modified the code accordingly. Do you think we need to split the slot filling and intent detection dataset btw?

Hi @yana-xuyan, can we separate the tasks into different `seacrowd` subsets (similar to #235)?

2024-01-08 04:51 UTC, yana-xuyan commented
Okie. Thank you Holy!

2024-01-09 15:04 UTC, SamuelCahyawijaya approved these changes
Hi @yana-xuyan, thank you for contributing. Tested and LGTM! Let's wait for the review from @gentaiscool 👍🏻

2024-01-17 00:56 UTC, gentaiscool approved these changes
thanks Xuyan for the contribution. Lgtm.

2024-01-22 08:27 UTC, merged