Closes #209 | Implement the dataloader for UIT-VSMEC
SEACrowd/seacrowd-datahub pull request #229
Opened 2023-12-26 05:21 UTC by jen-santoso

Please name your PR after the issue it closes. You can use the following line: "Closes #209 " where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-07 13:54 UTC, sabilmakbar requested changes
init review

2024-01-08 02:41 UTC, jen-santoso commented
OK, fixed for init review; please continue.

2024-01-09 07:36 UTC, jamesjaya approved these changes
tested, lgtm

2024-01-10 16:36 UTC, sabilmakbar reviewed
dataloader tested and ok, last nits from formatter

2024-01-10 16:36 UTC, sabilmakbar commented on seacrowd/sea_datasets/uit_vsmec/uit_vsmec.py
> +_DESCRIPTION = """\
nit: consider making it multiline since it exceeds 250 char

2024-01-10 16:36 UTC, sabilmakbar commented on seacrowd/sea_datasets/uit_vsmec/uit_vsmec.py
> +import pandas as pd
nit from formatter
```suggestion
import datasets
import pandas as pd

from seacrowd.utils import schemas
from seacrowd.utils.configs import SEACrowdConfig
from seacrowd.utils.constants import Tasks, Licenses
```

2024-01-14 07:38 UTC, jen-santoso commented
> dataloader tested and ok, last nits from formatter

OK fixed the formatting, please check

2024-01-15 15:42 UTC, sabilmakbar approved these changes
LGTM! Thanks, @jen-santoso!

2024-01-15 15:42 UTC, merged