PhoATIS Intent Classification
SEACrowd/seacrowd-datahub pull request #232
Opened 2023-12-26 08:09 UTC by dehanalkautsar

#139 . (Not closed as this is only one of two tasks in the dataset).

### Note
- Add some intent labels (i.e. `day_name`, `aicraft#flight`, `airline#flight`, `airfare#flight_time`) that haven't appeared in the datasets' constant label, but occur in some examples.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-03 03:00 UTC, gentaiscool requested changes
minor changes required

2024-01-03 03:00 UTC, gentaiscool commented on seacrowd/sea_datasets/phoatis_intent_cls/phoatis_intent_cls.py
> +                data_slot[idx] = data_slot[idx].split()
I think you don't need this line. You can split the data_slot on Line 193

2024-01-03 06:28 UTC, dehanalkautsar commented
Hi @gentaiscool, I have fixed the minor changes that are required.

2024-01-03 14:09 UTC, sabilmakbar commented
Hi @holylovenia @gentaiscool, since this is a multitask dataset and there's another PR of #235 for the same dataset, I'm thinking of unifying it rather than having 2 different dataloader scripts. 

Fortunately, both the assignee and the reviewers are the same. wdyt?

2024-01-03 14:31 UTC, dehanalkautsar commented
> Hi @holylovenia @gentaiscool, since this is a multitask dataset and there's another PR of #235 for the same dataset, I'm thinking of unifying it rather than having 2 different dataloader scripts.
> 
> Fortunately, both the assignee and the reviewers are the same. Should we close one of the PRs and discuss on the other one? wdyt?

I agree with that. Should we close this PR and discuss it on the other one?

2024-01-04 08:43 UTC, holylovenia commented
@sabilmakbar @dehanalkautsar I agree since PhoATIS Intent Classification and PhoATIS Slot Filling should be unified as a PhoATIS dataloader according to #139. I'll close this PR. Let's move to #235.

cc: @gentaiscool

2024-01-04 08:43 UTC, closed without merging