Closes #50 | Create dataset loader for TCOPE
SEACrowd/seacrowd-datahub pull request #239
Opened 2023-12-27 02:15 UTC by elyanah-aco

Closes #50.

### Notes
- Decided not to implement schema for dependency parsing task. Corpus has dependency-parsed text but no information on grammatical relationships between words. Essentially it's similar to just sequence labeling. 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-07 15:04 UTC, sabilmakbar requested changes
init review

2024-01-07 15:04 UTC, sabilmakbar commented on seacrowd/sea_datasets/tcope/tcope.py
> +                    "divided.tweet": datasets.Value("string"),
suggestion: although it can differ from the source col naming, the ideal col naming should contain alphanumeric and underscore only w/o spaces

2024-01-09 06:56 UTC, jamesjaya approved these changes
tested, lgtm

2024-01-10 18:24 UTC, sabilmakbar reviewed
one nit

2024-01-10 18:24 UTC, sabilmakbar commented on seacrowd/sea_datasets/tcope/tcope.py
> +_SUPPORTED_TASKS = [Tasks.POS_TAGGING]
I think we shd add `DEPENDENCY_PARSING` task regardless of no implementation in SEACrowd Schema.

For the testing purpose, I can test it separately by commenting the `DEPENDENCY_PARSING` for SEACrowd Schema in POS Tagging and test for `source` implementation for both tasks.

wdyt, @elyanah-aco?

cc @holylovenia @SamuelCahyawijaya

2024-01-10 18:31 UTC, sabilmakbar commented
tested using these two:
- for all tasks:
`python -m tests.test_seacrowd_source_only seacrowd/sea_datasets/tcope/tcope.py`
- for `POS_TAGGING` only:
`python -m tests.test_seacrowd seacrowd/sea_datasets/tcope/tcope.py`

2024-01-10 18:35 UTC, sabilmakbar commented
Btw why do we have a discrepancy of # of data between `_DESCRIPTION` vs actual examples that I obtained via test script `load_dataset`?

In test script, I get 2,520,719 data whereas in `_DESCRIPTION` it's only 1,048,576

Do you encounter this one too, @elyanah-aco @jamesjaya?

2024-01-10 23:15 UTC, elyanah-aco commented
@sabilmakbar 

Added dependency parsing task.

The no. of rows in `_DESCRIPTION` is wrong, I opened the file in Excel at first which couldn't load all the data. Thanks for pointing that out!

2024-01-11 04:11 UTC, sabilmakbar commented
So, does the number of rows in the data that you refer to match mine? @elyanah-aco. If yes, you may change it in desc to match with actual numbers, then I'll approve it afterward.

And for @jen-santoso, does the number of data based on dry-run matched w/ mine?

2024-01-11 05:53 UTC, elyanah-aco commented
I'm getting 2,520,712 examples, @jamesjaya can you let me know how many examples you got during testing?

2024-01-12 03:16 UTC, sabilmakbar commented
Maybe I was getting it wrong. Now the number matches. Thanks for your contributions, @elyanah-aco and @jamesjaya!

2024-01-12 03:16 UTC, sabilmakbar approved these changes
lgtm!

2024-01-12 03:16 UTC, merged