Closes #53 | Implement dataloader for IndoCamRest
SEACrowd/seacrowd-datahub pull request #257
Opened 2023-12-29 07:58 UTC by dehanalkautsar

Closes #53.

### Note
- For the fields in the TOD SEACrowd Schema, I left the `turn_label` field in this dataloader as an empty array because this dataset does not have them.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-17 08:54 UTC, holylovenia requested changes
Hi @dehanalkautsar, LGTM! The dataloader works well. I need you to remove the changes to `constant.py` and `schemas/` though.

2024-01-17 13:11 UTC, dehanalkautsar commented
Okay @holylovenia, those changes have been removed👍

2024-01-18 07:02 UTC, holylovenia approved these changes
Thanks for the changes, @dehanalkautsar 😄

2024-01-18 19:22 UTC, jamesjaya approved these changes

2024-01-18 19:23 UTC, merged