Closes #216 |  Create dataset loader for Mozilla Pontoon
SEACrowd/seacrowd-datahub pull request #260
Opened 2023-12-30 04:54 UTC by elyanah-aco

Closes #216.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-17 12:05 UTC, holylovenia requested changes
Hi @elyanah-aco, thanks for the dataloader! I believe there are some mistakes when separating the data into subsets since the `mozilla_pontoon_tgl_seacrowd_t2t` and `mozilla_pontoon_ind_seacrowd_t2t` give almost identical results as shown below:

```
DatasetDict({
    train: Dataset({
        features: ['id', 'text_1', 'text_2', 'text_1_name', 'text_2_name'],
        num_rows: 3559829
    })
})

Train 10
{'id': '20',
 'text_1': 'Adyghe',
 'text_1_name': 'eng',
 'text_2': 'Адыга',
 'text_2_name': 'tgl'}

Train 200
{'id': '200',
 'text_1': 'Having a profile is not required to contribute though it is '
           'helpful, see why below.',
 'text_1_name': 'eng',
 'text_2': 'Ахалархәразы ахатә ҷыдахәра амазаара хымԥадатәӡом, уи шхәарҭоугьы.',
 'text_2_name': 'tgl'}

Train 500
{'id': '600',
 'text_1': 'Yes, we especially want your voice! Part of the aim of Common '
           'Voice is to gather as many different accents as possible so that '
           'voice recognition services work equally well for everyone. This '
           'means donations from non-native speakers are particularly '
           'important.',
 'text_1_name': 'eng',
 'text_2': 'Ааи, ҳара еиҳаракгьы уара убжьы оуп иаҳҭахәу! Common Voice хықәкыс '
           'иамоуп еиуеиԥшым аҳәашьақәа реизгара, абжьеилыргаратә маҵзурақәа '
           'зегьы рзы, доусы ҷыдала изнеиларатәы. Уи иаанаго, абызшәа '
           'ныҟәзымго рлагала аҵакы ду шамо оуп.',
 'text_2_name': 'tgl'}

Train 2000
{'id': '2000',
 'text_1': 'Settings…',
 'text_1_name': 'eng',
 'text_2': 'Peuatô...',
 'text_2_name': 'tgl'}

Train 20000
{'id': '20000',
 'text_1': 'OPML Files',
 'text_1_name': 'eng',
 'text_2': 'OPML-lêers',
 'text_2_name': 'tgl'}

Train 200000
{'id': '200000',
 'text_1': 'Exit Responsive Design Mode',
 'text_1_name': 'eng',
 'text_2': 'প্রতিক্রিয়াশীল ডিজাইন মোড থেকে প্রস্থান করুন',
 'text_2_name': 'tgl'}

Train 2000000
{'id': '2000000',
 'text_1': 'Email link',
 'text_1_name': 'eng',
 'text_2': 'ایمیل لینک',
 'text_2_name': 'tgl'}
```

The only difference is the `mozilla_pontoon_ind_seacrowd_t2t`'s output uses `'text_2_name': 'ind'` instead of `'text_2_name': 'tgl'`. Furthermore, values in `text_2` are neither in Tagalog nor Indonesian. I have yet to check the other subsets, but I suspect they will experience the same problem.

In addition, here are a couple of changes that I would suggest:

2024-01-17 12:05 UTC, holylovenia commented on seacrowd/sea_datasets/mozilla_pontoon/mozilla_pontoon.py
> +            name=f"{_DATASETNAME}_{lang}_source",
Use `eng_{lang}` instead of just `{lang}`.

2024-01-17 12:05 UTC, holylovenia commented on seacrowd/sea_datasets/mozilla_pontoon/mozilla_pontoon.py
> +            name=f"{_DATASETNAME}_{lang}_seacrowd_t2t",
Use `eng_{lang}` instead of just {lang}.

2024-01-17 22:45 UTC, elyanah-aco commented
@holylovenia Seems like dataset changed a bit since I first submitted the dataloader. Running tests for entire data and for each subset should now give correct results:

![image](https://github.com/SEACrowd/seacrowd-datahub/assets/77622465/ee3e3c3d-33c3-4374-9bc0-b8747b2944e2)
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/77622465/d296681f-0e67-4f7a-ba31-ccff43e3167d)
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/77622465/f4061796-926b-42bf-9c2d-a1a678c747d6)

2024-01-18 07:39 UTC, holylovenia commented
> Hi @elyanah-aco, thanks for the dataloader! I believe there are some mistakes when separating the data into subsets since the `mozilla_pontoon_tgl_seacrowd_t2t` and `mozilla_pontoon_ind_seacrowd_t2t` give almost identical results as shown below:
> 
> ```
> DatasetDict({
>     train: Dataset({
>         features: ['id', 'text_1', 'text_2', 'text_1_name', 'text_2_name'],
>         num_rows: 3559829
>     })
> })
> 
> Train 10
> {'id': '20',
>  'text_1': 'Adyghe',
>  'text_1_name': 'eng',
>  'text_2': 'Адыга',
>  'text_2_name': 'tgl'}
> 
> Train 200
> {'id': '200',
>  'text_1': 'Having a profile is not required to contribute though it is '
>            'helpful, see why below.',
>  'text_1_name': 'eng',
>  'text_2': 'Ахалархәразы ахатә ҷыдахәра амазаара хымԥадатәӡом, уи шхәарҭоугьы.',
>  'text_2_name': 'tgl'}
> 
> Train 500
> {'id': '600',
>  'text_1': 'Yes, we especially want your voice! Part of the aim of Common '
>            'Voice is to gather as many different accents as possible so that '
>            'voice recognition services work equally well for everyone. This '
>            'means donations from non-native speakers are particularly '
>            'important.',
>  'text_1_name': 'eng',
>  'text_2': 'Ааи, ҳара еиҳаракгьы уара убжьы оуп иаҳҭахәу! Common Voice хықәкыс '
>            'иамоуп еиуеиԥшым аҳәашьақәа реизгара, абжьеилыргаратә маҵзурақәа '
>            'зегьы рзы, доусы ҷыдала изнеиларатәы. Уи иаанаго, абызшәа '
>            'ныҟәзымго рлагала аҵакы ду шамо оуп.',
>  'text_2_name': 'tgl'}
> 
> Train 2000
> {'id': '2000',
>  'text_1': 'Settings…',
>  'text_1_name': 'eng',
>  'text_2': 'Peuatô...',
>  'text_2_name': 'tgl'}
> 
> Train 20000
> {'id': '20000',
>  'text_1': 'OPML Files',
>  'text_1_name': 'eng',
>  'text_2': 'OPML-lêers',
>  'text_2_name': 'tgl'}
> 
> Train 200000
> {'id': '200000',
>  'text_1': 'Exit Responsive Design Mode',
>  'text_1_name': 'eng',
>  'text_2': 'প্রতিক্রিয়াশীল ডিজাইন মোড থেকে প্রস্থান করুন',
>  'text_2_name': 'tgl'}
> 
> Train 2000000
> {'id': '2000000',
>  'text_1': 'Email link',
>  'text_1_name': 'eng',
>  'text_2': 'ایمیل لینک',
>  'text_2_name': 'tgl'}
> ```
> 
> The only difference is the `mozilla_pontoon_ind_seacrowd_t2t`'s output uses `'text_2_name': 'ind'` instead of `'text_2_name': 'tgl'`. Furthermore, values in `text_2` are neither in Tagalog nor Indonesian. I have yet to check the other subsets, but I suspect they will experience the same problem.
> 
> In addition, here are a couple of changes that I would suggest:

Hi @elyanah-aco, I tried again and still got similar results with the previous ones. I couldn't reproduce the results you attached. Is it possible the latest push missed a few commits?

Additionally, could you please remove the non-SEA languages from the `mozilla_pontoon_source` and `mozilla_pontoon_seacrowd_t2t` schema?

2024-01-18 08:29 UTC, elyanah-aco commented
@holylovenia That's strange, can confirm I didn't miss any commits and that results are still the same on my end. Maybe someone else can also test and see what they get?

Current source and seacrowd schemas also only contain SEA languages on my end, with config names checked via `dataset.info.config_name`:

![image](https://github.com/SEACrowd/seacrowd-datahub/assets/77622465/7798b3eb-d8ed-4a0a-9d64-7f5fc81ef442)

2024-01-18 08:48 UTC, holylovenia commented
> @holylovenia That's strange, can confirm I didn't miss any commits and that results are still the same on my end. Maybe someone else can also test and see what they get?
> 
> Current source and seacrowd schemas also only contain SEA languages on my end, with config names checked via `dataset.info.config_name`:
> 
> ![image](https://private-user-images.githubusercontent.com/77622465/297673570-7798b3eb-d8ed-4a0a-9d64-7f5fc81ef442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njc5OTIsIm5iZiI6MTcwNTU2NzY5MiwicGF0aCI6Ii83NzYyMjQ2NS8yOTc2NzM1NzAtNzc5OGIzZWItZDhlZC00YTBhLTlkNjQtN2Y1ZmM4MWVmNDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNDRkZDZjMTk5ZDQ3YmUyZWU0OTYzZDY1OWI1NTAzZjQ0ZGE1MmY4MGI3ODhmYmM3MDU3NGM2YTY1ODUzZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6LNJ7b0AX3P0fkqHUd5fI10BsIW4uObIue6KPo2ynw)

Yeah, that's strange. I even tried to remove my cache but nothing changed. Let's wait for @SamuelCahyawijaya's review.

2024-01-28 04:33 UTC, SamuelCahyawijaya commented
@holylovenia @elyanah-aco , I tested on my end and it seems to work as expected. I will approve this PR then.
<img width="1116" alt="Screenshot 2024-01-28 at 10 33 45 AM" src="https://github.com/SEACrowd/seacrowd-datahub/assets/2826602/c545fa7e-a1f0-4d9c-b304-265a32c279b3">

2024-01-28 04:33 UTC, SamuelCahyawijaya approved these changes
LGTM!

2024-01-29 05:27 UTC, holylovenia approved these changes
Thanks for checking, @SamuelCahyawijaya! LGTM too. Thanks for your hard work in implementing this dataloader, @elyanah-aco! 🎊

2024-01-29 05:27 UTC, merged