Closes #277 | Implemente dataloader for spamid_pair
SEACrowd/seacrowd-datahub pull request #281
Opened 2024-01-02 07:53 UTC by Alex-HaochenLi

Closes #277.

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-21 05:37 UTC, ljvmiranda921 reviewed
Hi @Alex-HaochenLi , thanks for this data loader PR. I just have one nit on class naming but the data loader works as expected! 👍

2024-01-21 05:37 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/spamid_pair/spamid_pair.py
> +class SpamidPair(datasets.GeneratorBasedBuilder):
```suggestion
class SpamidPairDataset(datasets.GeneratorBasedBuilder):
```

2024-01-21 08:03 UTC, Alex-HaochenLi commented
Hello @ljvmiranda921, I have revised and committed according to your review. Please have a check :)

2024-01-21 09:52 UTC, ryanignatius requested changes

2024-01-21 09:52 UTC, ryanignatius commented on seacrowd/sea_datasets/spamid_pair/__init__.py
> +from .utils.constants import Tasks
I encountered error when running the test
```
    from .utils.constants import Tasks
ModuleNotFoundError: No module named 'seacrowd.sea_datasets.spamid_pair.utils'
```

I think we can leave this `__init__.py` file empty

2024-01-22 03:17 UTC, ryanignatius approved these changes
reviewed and tested, LGTM

2024-01-23 15:38 UTC, ljvmiranda921 approved these changes
LGTM!

2024-01-23 15:39 UTC, merged