Add Loader for XCOPA
SEACrowd/seacrowd-datahub pull request #286
Opened 2024-01-03 10:00 UTC by FawwazMayda

Create loader for XCOPA for `th` (thailand) and `vi` (Vietnamese)

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### Th
![Screenshot 2024-01-03 at 16 59 27](https://github.com/SEACrowd/seacrowd-datahub/assets/33770567/6861df83-ecc8-40a6-acf8-308b26e36d46)

`python -m tests.test_seacrowd seacrowd/sea_datasets/xcopa_th/xcopa_th.py --subset_id xcopa`

![Screenshot 2024-01-03 at 16 59 59](https://github.com/SEACrowd/seacrowd-datahub/assets/33770567/257d09a9-76b1-4e7c-82b6-9307f64caeec)

### Vi
![Screenshot 2024-01-03 at 16 56 37](https://github.com/SEACrowd/seacrowd-datahub/assets/33770567/cbf9e276-2e98-4ba0-a09f-ecb4378e9feb)

`python -m tests.test_seacrowd seacrowd/sea_datasets/xcopa_vi/xcopa_vi.py --subset_id xcopa`

![Screenshot 2024-01-03 at 16 57 45](https://github.com/SEACrowd/seacrowd-datahub/assets/33770567/ab8a8ae1-9a95-42ad-9026-ba099fb260ea)

2024-01-03 14:12 UTC, sabilmakbar commented
Hi @FawwazMayda, thanks for contributing on this dataloader!

May I know why Indonesian language is being skipped? Both the datacard and the source dataset has `id` as one of the supported languages, tho.

2024-01-03 14:14 UTC, FawwazMayda commented
Currently it already has `id` in `seacrowd/xcopa` so because its already implemented that is why I left with implementing `th` and `vie`

<img width="1417" alt="Screenshot 2024-01-03 at 21 14 12" src="https://github.com/SEACrowd/seacrowd-datahub/assets/33770567/1f560965-bd5b-4b21-80f7-a00e9a638dd3">

2024-01-03 14:17 UTC, sabilmakbar commented
In that case, would you extend the script on `sea_datasets/xcopa` to cover `tha` and `vie` aswell? This shd be similar to this previously-merged PR, you may refer the implementation to here:
https://github.com/SEACrowd/seacrowd-datahub/pull/125

2024-01-21 16:20 UTC, FawwazMayda commented
updated @sabilmakbar I added all those languages into single `xcopa.py`

2024-01-22 05:56 UTC, holylovenia requested changes
Hi @FawwazMayda, thanks a lot for your hard work!! 💪 Could I please request for these changes?

1. Re-arrange the field-value mapping for the `seacrowd_qa` schema a bit.

Given this `source` schema:
```
{
    'premise': premise,
    'choice1': choice1,
    'choice2': choice2,
    'question': reasoning_type,
    'label': label_id,
    'idx': id,
    'changed': changed_type
}
```

Let's use this `seacrowd_qa` structure:
```
{
    'id': id,
    'question_id': id,
    'document_id': id,
    'question': '',
    'type': 'multiple_choice',
    'choices': [
        choice1,
        choice2
    ],
    'context': premise,
    'answer': [
        choices[label_id]
    ],
    'meta': {
        'reasoning_type': reasoning_type,
        'is_changed': changed_type
    }
}
```

2. Use `_LANGUAGES = ["ind", "tha", "vie"]` instead of `_LANGUAGES = ["ind", "th", "vie"]`

3. Use `Licenses.CC_BY_4_0.value` instead of `"Unknown"` for `_LICENSE`.

2024-01-31 03:47 UTC, holylovenia approved these changes
LGTM! 👍 Thanks a lot, @FawwazMayda! Let's wait for @sabilmakbar's review now.

2024-01-31 03:58 UTC, sabilmakbar reviewed
in [L11](https://github.com/SEACrowd/seacrowd-datahub/pull/286/files#diff-8054d53da69e3318748bfe9fc8843fe3a1e0e82613dbf86c356fabda660d71cdR11), add `License` object import to define the `_LICENSE` value correctly

```from seacrowd.utils.constants import Tasks, Licenses```

2024-01-31 03:58 UTC, sabilmakbar commented on seacrowd/sea_datasets/xcopa/xcopa.py
> +_LICENSE = "Licenses.CC_BY_4_0.value"
this is an Enum object, not a string

```suggestion
_LICENSE = Licenses.CC_BY_4_0.value
```

2024-01-31 04:24 UTC, FawwazMayda commented on seacrowd/sea_datasets/xcopa/xcopa.py
> +_LICENSE = "Licenses.CC_BY_4_0.value"
added

2024-02-01 13:23 UTC, sabilmakbar commented
Hi @FawwazMayda, can you try to run the formatter check and fix it accordingly?
I found some import & readability suggestions found like traling whitespace in a line, unused imports, fix reference of internal var in config creation (`l` to `lang`)

```sh
make check_file=seacrowd/sea_datasets/xcopa/xcopa.py
```

2024-02-02 16:48 UTC, FawwazMayda commented
applied

2024-02-02 16:48 UTC, FawwazMayda commented
updated @sabilmakbar

2024-02-04 12:37 UTC, sabilmakbar approved these changes
LGTM! Thanks @FawwazMayda and @holylovenia, merging this...

2024-02-04 12:37 UTC, merged