Closes #219 | Create dataloader for scb-mt-en-th-2020
SEACrowd/seacrowd-datahub pull request #287
Opened 2024-01-03 12:58 UTC by jen-santoso

Please name your PR after the issue it closes. You can use the following line: "Closes #219 " where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-03 13:00 UTC, jen-santoso commented
Hello reviewers,

In addition to the PR, I would like to report that the DataCatalogue link in #219 does not work.
Instead, I found this link works for this dataset: https://seacrowd.github.io/seacrowd-catalogue/card.html?scb-mt-en-th-2020.

Therefore, one clarification: Should the dataset name be scb-mt-en-th or scb-mt-en-th-2020?
I think the dataset name reported in the title, card, and dataloader name should be unified.
Please let me know which dataset name is the correct one.

2024-01-17 12:18 UTC, holylovenia commented
> Hello reviewers,
> 
> In addition to the PR, I want to let you know (as reported in the comment section of issue #219) that the DataCatalogue link cannot be opened from here. Instead, I found this link works for this dataset: https://seacrowd.github.io/seacrowd-catalogue/card.html?scb-mt-en-th-2020.
> 
> Therefore, one clarification: Should the dataset name be scb-mt-en-th or scb-mt-en-th-2020? (UPDATE: it will be implemented with the `snakecase` dataloader name) I think the dataset name reported in the title, card, and dataloader name should be unified. Please let me know which dataset name is the correct one.

Hi @jen-santoso, let's stick with `scb_mt_en_th`.
I'll run this by @SamuelCahyawijaya to see what triggers the incorrect URL being generated.

2024-01-18 07:50 UTC, holylovenia commented on seacrowd/sea_datasets/scb_mt_en_th/scb_mt_en_th.py
> +            language_pair = [SEACROWD_TO_SOURCE_LANGCODE_DICT[lang] for lang in self.config.name.split("_")[1:3]]
`1:3` --> `4:6`

2024-01-18 08:44 UTC, holylovenia commented on seacrowd/sea_datasets/scb_mt_en_th/scb_mt_en_th.py
> +                language_pair = [SEACROWD_TO_SOURCE_LANGCODE_DICT[lang] for lang in self.config.name.split("_")[1:3]]
`1:3` --> `4:6`

2024-01-18 08:44 UTC, holylovenia commented on seacrowd/sea_datasets/scb_mt_en_th/scb_mt_en_th.py
> +                source, target = self.config.name.split("_")[1:3]
`1:3` --> `4:6`

2024-01-18 08:47 UTC, holylovenia requested changes
Hi @jen-santoso, thanks for your dataloader!! Could you please add `_LANGUAGES = ["tha", "eng"]`? Also, I've got a few suggestions above.

2024-01-22 05:58 UTC, holylovenia approved these changes
Thanks for the changes, @jen-santoso! Good work as always~ Let's wait for @jamesjaya's review.

2024-01-22 12:39 UTC, jamesjaya approved these changes
tested, lgtm

2024-01-22 12:39 UTC, merged