Closes #180 | Implement Indommlu dataloader
SEACrowd/seacrowd-datahub pull request #324
Opened 2024-01-15 00:39 UTC by chenxwh

Found 2 invalid examples in the original datasets: the answer is not in the options. The implemented dataloader skips those 2 examples.

```
(4223)
{ 'question': 'Keberadaan jumlah belalang warna hijau dan coklat di sawah pada awalnya seimbang. Setelah padi dipanen, ternyata berpengaruh pada jumlah belalang berwarna hijau yang jumlahnya semakin menurun. Hal ini disebabkan karena ….',
 'options': "['A. belalang berwarna hijau tidak dapat berkembang biak', 'B. jumlahnya berkurang karena dimakan oleh pemangsa', 'C. tidak dapat beradaptasi dengan lingkungan sawah', 'D. adanya pengaruh predasi antara sesama belalang']",
 'answer': 'E'}

(14150)
{'question': 'Ibu Meminta Nana menyapu halaman, tetapi ia sedang belajar, kalimat penolakan yang tetap dalah.....',
 'options': "['A. Aku tidak mau ibu', 'B. Maaf ibu aku sedang belajar', 'C. Ibu saja yang menyapu']",
 'answer': 'D'}
```

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-29 05:53 UTC, holylovenia requested changes
Hi @chenxwh, thanks for implementing this dataloader. I have some suggestions.

1. Could you please add an empty `__init__.py`?

2. Could you please remove the letters from the answer options?

From this:
```
{'answer': ['C. Seharusnya Ibra tidur lebih awal agar sampai di sekolah tepat waktunya'],
 'choices': ['A. Seharusnya orang tuanya melarang Ibra tidur hingga larut malam',
             'B. Salah sendiri ia tidur larut malam',
             'C. Seharusnya Ibra tidur lebih awal agar sampai di sekolah tepat waktunya',
             'D. Seharusnya Ibra tidak perlu nonton TV hingga larut malam'],
... }
```

Becomes this:

```
{'answer': ['Seharusnya Ibra tidur lebih awal agar sampai di sekolah tepat waktunya'],
 'choices': ['Seharusnya orang tuanya melarang Ibra tidur hingga larut malam',
             'Salah sendiri ia tidur larut malam',
             'Seharusnya Ibra tidur lebih awal agar sampai di sekolah tepat waktunya',
             'Seharusnya Ibra tidak perlu nonton TV hingga larut malam'],
```

3. Could we have more `seacrowd` schemas to separate the indigenous language subjects?

Current subsets:
- `indommlu_source`
- `indommlu_seacrowd_qa`

Suggested subsets:
- `indommlu_source` --> contains everything
- `indommlu_seacrowd_qa` --> contains everything
- `indommlu_ind_seacrowd_qa` --> everything - indigenous language subjects (e.g., Lampungic, Makassarese, Balinese, etc.)
- `indommlu_{lang}_seacrowd_qa` --> for lang in indigenous language subjects (e.g., Lampungic, Makassarese, Balinese, etc.) Example: `indommlu_ban_seacrowd_qa` for Balinese language subject QAs.

4. Update `_LANGUAGES` to contain `ind` as well as all the other indigenous languages in the dataset.

2024-02-02 13:55 UTC, chenxwh commented
Thanks for the suggestions! Modified accordingly with added extra langs that have iso code from https://iso639-3.sil.org/code_tables/639/data

2024-02-04 06:09 UTC, holylovenia requested changes
Hi @chenxwh, thanks a lot for the changes. 🙏 Could I please request a few other adjustments?

- `indommlu_ind_seacrowd_qa` to include the Indonesian language subject and other non-language subjects (e.g., History, Math, Geography, etc.)

2024-02-04 06:09 UTC, holylovenia commented on seacrowd/sea_datasets/indommlu/indommlu.py
> +    "SMA": "SMA",
Add this comment: `"# SMA --> high school level"`.

2024-02-04 06:09 UTC, holylovenia commented on seacrowd/sea_datasets/indommlu/indommlu.py
> +    "SD": "SD",
Add this comment: `"# SD --> elementary school level"`.

2024-02-04 06:09 UTC, holylovenia commented on seacrowd/sea_datasets/indommlu/indommlu.py
> +    "SMP": "SMP",
Add this comment: `"# SMP --> junior high school level"`.

2024-02-05 22:32 UTC, chenxwh commented
Thank you for the comments, I have updated accordingly, apart from adding `"min"` as there is no "Minangkabau language" but only ""Minangkabau culture".

2024-02-06 10:10 UTC, holylovenia commented
Replacing @gentaiscool with @ryanignatius due to no response.

2024-02-09 07:38 UTC, holylovenia approved these changes
Tried and tested. Works well! Thanks a lot for the changes and your prompt responses, @chenxwh! 😄

2024-02-12 07:24 UTC, ryanignatius commented on seacrowd/sea_datasets/indommlu/indommlu.py
> +        BUILDER_CONFIGS.append(lang_config)
please also add the source config for all languages
`name=f"{_DATASETNAME}_{lang}_source"`

2024-02-12 10:03 UTC, chenxwh commented
oh really? There is no such "subset distinction" in the source datasets. thought @holylovenia suggested we add those just for seacrowd scheme?

2024-02-12 13:12 UTC, holylovenia commented
> oh really? There is no such "subset distinction" in the source datasets. thought @holylovenia suggested we add those just for seacrowd scheme?

I think @ryanignatius suggested it so all the subset IDs (i.e., `"indommlu"` and `"indommlu_{lang}"`) can pass the unit test: `python -m tests.test_seacrowd seacrowd/sea_datasets/indommlu/indommlu.py --subset_id={subset_id}`. That being said, I think only having `indommlu_source` as the only source schema is sufficient since all the subsets follow the same schemas.

2024-02-13 13:59 UTC, ryanignatius commented
> > oh really? There is no such "subset distinction" in the source datasets. thought @holylovenia suggested we add those just for seacrowd scheme?
> 
> I think @ryanignatius suggested it so all the subset IDs (i.e., `"indommlu"` and `"indommlu_{lang}"`) can pass the unit test: `python -m tests.test_seacrowd seacrowd/sea_datasets/indommlu/indommlu.py --subset_id={subset_id}`. That being said, I think only having `indommlu_source` as the only source schema is sufficient since all the subsets follow the same schemas.

ah okay got it,
sorry I miss the comment to add for seacrowd schema only

2024-02-13 13:59 UTC, ryanignatius approved these changes

2024-02-13 14:00 UTC, merged