Closes #183 | Implement wongnai_reviews dataloader
SEACrowd/seacrowd-datahub pull request #325
Opened 2024-01-15 02:05 UTC by chenxwh

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-31 09:17 UTC, jen-santoso requested changes
Hi @chenxwh, thanks for implementing the dataloader. 

The Task is listed as `Text classification` in the issue card.
Is there a case where multiple classes exist? 
If no, please change the `_SUPPORTED_TASKS` to `Tasks.TEXT_CLASSIFICATION`, along with the other suggestions here. 
Otherwise, please consider only the suggestions in line 68, 72, and 76.

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +            name=f"{_DATASETNAME}_seacrowd_text_multi",
following the task type, the schema (and therefore the config name) should be `seacrowd_text`. This also applies here and throughout the code.

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +        if self.config.schema == "source":
```suggestion
        star_rating = ["1", "2", "3", "4", "5"]
        if self.config.schema == "source":
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +                    "star_rating": datasets.ClassLabel(names=["1", "2", "3", "4", "5"]),
```suggestion
                    "star_rating": datasets.ClassLabel(names=star_rating),
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +            features = schemas.text_multi_features(["1", "2", "3", "4", "5"])
```suggestion
            features = schemas.text_features(label_names=star_rating)
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +_SUPPORTED_TASKS = [Tasks.ASPECT_BASED_SENTIMENT_ANALYSIS]
```suggestion
_SUPPORTED_TASKS = [Tasks.TEXT_CLASSIFICATION]
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +                    yield i, {"id": str(i), "text": row[0], "labels": [row[1]]}
```suggestion
                    yield i, {"id": str(i), "text": row[0], "label": row[1]}
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +        elif self.config.schema == "seacrowd_text_multi":
```suggestion
        elif self.config.schema == "seacrowd_text":
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +            name=f"{_DATASETNAME}_seacrowd_text_multi",
```suggestion
            name=f"{_DATASETNAME}_seacrowd_text",
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +            schema="seacrowd_text_multi",
```suggestion
            schema="seacrowd_text",
```

2024-01-31 09:17 UTC, jen-santoso commented on seacrowd/sea_datasets/wongnai_reviews/wongnai_reviews.py
> +        elif self.config.schema == "seacrowd_text_multi":
```suggestion
        elif self.config.schema == "seacrowd_text":
```

2024-02-01 10:12 UTC, chenxwh commented
Thanks for the suggestions! Made suitable changes for the new task class.

2024-02-11 08:11 UTC, jen-santoso approved these changes

2024-02-14 05:12 UTC, holylovenia commented
Replacing @danjohnvelasco with @MJonibek.

2024-02-14 18:10 UTC, MJonibek approved these changes
@chenxwh thank you for working on this dataloader. Checked, LGTM.

2024-02-14 18:20 UTC, merged