Closes #182. | Implement dataloader for roots_vi_ted
SEACrowd/seacrowd-datahub pull request #329
Opened 2024-01-16 00:20 UTC by chenxwh

Closes #182.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-02-04 06:39 UTC, ryanignatius commented
hi @chenxwh thank you for the PR

about the data, since it is publicly accessible after user has accepted the dataset's acknowledgement, could we append "Before using this dataloader, please accept the acknowledgement at https://huggingface.co/datasets/bigscience-data/roots_vi_ted_talks_iwslt and use huggingface-cli login for authentication." to the _DESCRIPTION?

also remove `train-00000-of-00001.parquet` file from data directory and change _LOCAL to false

2024-02-04 06:44 UTC, ryanignatius commented on seacrowd/sea_datasets/roots_vi_ted/roots_vi_ted.py
> +            features["meta"] = {
I think we can omit this meta here and only use the text for the seacrowd_ssp schema

2024-02-04 06:50 UTC, ryanignatius commented on seacrowd/sea_datasets/roots_vi_ted/roots_vi_ted.py
> +class RootsViTed(datasets.GeneratorBasedBuilder):
please add `Dataset` suffix to class name
```suggestion
class RootsViTedDataset(datasets.GeneratorBasedBuilder):
```

2024-02-05 21:49 UTC, chenxwh commented
Thank you! Updated accordingly

2024-02-06 10:10 UTC, holylovenia commented
Replacing @gentaiscool with @MJonibek due to no response.

2024-02-06 13:37 UTC, MJonibek requested changes
Hello @chenxwh , everything works, just small formating is needed. Please, can you run 

`make check_file=seacrowd/sea_datasets/roots_vi_ted/roots_vi_ted.py`

<img width="970" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/44943993/a967441c-5761-4dca-b3cc-9e2e4e13190a">

To solve two warnings you need to delete `import os` and delete space in the end of the 35 line.

2024-02-06 14:08 UTC, chenxwh commented
thanks @MJonibek just updated

2024-02-06 14:12 UTC, MJonibek approved these changes
@chenxwh Thank you for the fast response, LGTM

2024-02-12 07:02 UTC, ryanignatius approved these changes

2024-02-12 07:03 UTC, merged