Closes #193 | Create dataset loader for MALINDO Morph
SEACrowd/seacrowd-datahub pull request #332
Opened 2024-01-19 11:01 UTC by danjohnvelasco

Closes #193

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

> Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.

This dataset is a lexicon. It does not support any tasks. This case is similar to https://github.com/SEACrowd/seacrowd-datahub/pull/155

2024-01-29 06:08 UTC, holylovenia approved these changes
Other than one minor fix below, I have nothing more to suggest. LGTM!

2024-01-29 06:08 UTC, holylovenia commented on seacrowd/sea_datasets/malindo_morph/malindo_morph.py
> +MALINDO Morph is a morphological dictionary for Malay (bahasa Melayu) and Indosian (bahasa Indonesia) language.
"Indosian" --> "Indonesian"

2024-02-04 09:03 UTC, danjohnvelasco commented
> Other than one minor fix below, I have nothing more to suggest. LGTM!

Fixed!

2024-02-06 10:11 UTC, holylovenia commented
Replacing @gentaiscool with @jen-santoso due to no response.

2024-02-11 08:03 UTC, jen-santoso requested changes
Hi @danjohnvelasco, thank you for the dataloader implementation.

So this case is a source-only, right? The dataloader runs well, just two nits here and the dataloader's good to go!

2024-02-24 14:44 UTC, danjohnvelasco commented
> Hi @danjohnvelasco, thank you for the dataloader implementation.
> 
> So this case is a source-only, right? The dataloader runs well, just two nits here and the dataloader's good to go!

Hi @jen-santoso, thanks for the review. Yes, this is source-only. Your suggested changes are commited.

2024-02-25 06:54 UTC, jen-santoso requested changes
Sorry, one last nit. Other than that, it's LGTM

2024-02-25 06:54 UTC, jen-santoso commented on seacrowd/sea_datasets/malindo_morph/malindo_morph.py
> +
The description is duplicate from `_DESCRIPTION`, so let's remove this part
```suggestion
```

2024-03-07 08:16 UTC, jen-santoso approved these changes

2024-03-07 08:17 UTC, merged