Closes #305 | Implement dataloader for UIT_ViOCD
SEACrowd/seacrowd-datahub pull request #335
Opened 2024-01-20 12:42 UTC by Alex-HaochenLi

Closes #305. 

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-01-31 07:19 UTC, jen-santoso requested changes
Hi @Alex-HaochenLi, thank you for implementing the dataloader.

Unfortunately, the dataloader couldn't run here, as `_generate_examples` is missing `split: str` as parameter. 
There are two choices:
1. change line 130 to 
`    def _generate_examples(self, filepath: Path, split: str) -> Tuple[int, Dict]:`
and change `dev` to `val` in line 125
2. remove `split` parameters in line 111, 118, 125.
I would recommend option 2 as parameter `split` is not used in `_generate_examples`

After fixing this, I will continue the review.

2024-01-31 09:04 UTC, Alex-HaochenLi commented
Hi @jen-santoso, I have revised the code based on option 2. Please have a check.

2024-02-01 07:43 UTC, jen-santoso approved these changes

2024-02-01 07:43 UTC, jen-santoso commented
Hi @Alex-HaochenLi, thank you for the revision. LGTM and let's wait for @danjohnvelasco to review!

2024-02-14 05:11 UTC, holylovenia commented
Replacing @danjohnvelasco with @holylovenia.

2024-02-19 06:39 UTC, holylovenia requested changes
Hi @Alex-HaochenLi, everything works well. There's only one minor change requested:

2024-02-19 06:39 UTC, holylovenia commented on seacrowd/sea_datasets/uit_viocd/uit_viocd.py
> +_SUPPORTED_TASKS = [Tasks.INTENT_CLASSIFICATION]
Could you please pull from the `main` branch and change this to `Tasks.COMPLAINT_DETECTION`?

2024-02-20 02:39 UTC, Alex-HaochenLi commented
Hi @holylovenia, I have updated the supported tasks. Please have a check.

2024-02-20 05:29 UTC, holylovenia approved these changes
LGTM! Thanks a lot, @Alex-HaochenLi. 🙏

2024-02-20 05:29 UTC, merged