Closes #202 | Implement dataloader for WIT
SEACrowd/seacrowd-datahub pull request #374
Opened 2024-01-23 17:10 UTC by raileymontalan

Closes [#202 ](https://github.com/SEACrowd/seacrowd-datahub/issues/202).

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/wit/wit.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/wit/wit.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-02-09 20:58 UTC, ljvmiranda921 reviewed
Just missing an `__init__.py` file and some nits
But other than that, the dataloader works properly :) Thank you!

2024-02-09 20:58 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/wit/wit.py
> +logger = datasets.logging.get_logger(__name__)
Let's remove this if we're not using it

```suggestion
```

2024-02-12 13:49 UTC, holylovenia requested changes
Hi @raileymontalan, I read [Section 3.2 of the dataset's paper](https://arxiv.org/pdf/2103.01913.pdf). This explains why there are multiple texts related to the image.

For the `texts` in the `seacrowd_imtext` schemas, could we please use the value of `caption_reference_description`? If it's `None`, then we use the value of `caption_attribution_description`. If it's also `None`, then we use the value of `caption_alt_text_description`.

In addition, could you also please note down which description is used for the data instance as a value of the `context` in the `seacrowd_imtext`?

2024-02-12 23:03 UTC, ljvmiranda921 commented
@holylovenia I think that logic works well and would love to see this change 👍 . Also stressing that the `context` is kinda important here because they relate to the informativeness of the image caption/description.

2024-02-28 06:02 UTC, holylovenia requested changes
Hi @raileymontalan, could you please remove all changes aside from those applied to `seacrowd/sea_datasets/wit/*`?

2024-02-28 06:56 UTC, raileymontalan commented
Unnecessary commits have been removed. @holylovenia

2024-03-04 06:58 UTC, holylovenia approved these changes
Thanks for the changes, @raileymontalan! The dataloader works well on my side. One last request:

Could you please append this to `_DESCRIPTION`?

"Since the dataset contains multiple references, following Section 3.2 of the dataset's paper, the `seacrowd_imtext` subsets specify which reference is used for each data instance's `texts` via `context` in `metadata`."

Then, @ljvmiranda921 can merge this dataloader after he gives his approval.

2024-03-06 02:02 UTC, raileymontalan commented
> Thanks for the changes, @raileymontalan! The dataloader works well on my side. One last request:
> 
> Could you please append this to `_DESCRIPTION`?
> 
> "Since the dataset contains multiple references, following Section 3.2 of the dataset's paper, the `seacrowd_imtext` subsets specify which reference is used for each data instance's `texts` via `context` in `metadata`."
> 
> Then, @ljvmiranda921 can merge this dataloader after he gives his approval.

Hi @holylovenia, added to the description. Thanks!

2024-03-06 03:26 UTC, holylovenia approved these changes
Thank you so much, @raileymontalan! 🙏 Merging now.

2024-03-06 03:27 UTC, merged