Closes #192 | Create dataset loader for MALINDO_parallel
SEACrowd/seacrowd-datahub pull request #385
Opened 2024-01-27 16:17 UTC by bryanwilie

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-02-03 13:11 UTC, MJonibek commented
Please can you add `__init__.py` file, and also remove all comments (especially TODO)

2024-02-03 17:11 UTC, bryanwilie commented
Hi @MJonibek, that's just done. Thank you for reviewing!

2024-02-14 20:39 UTC, ljvmiranda921 reviewed
Just a few small nits but the data loader works properly :)
Please rerun `make check_file` as well to ensure that the formatting is consistent with the other implementations.

2024-02-14 20:39 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/malindo_parallel/malindo_parallel.py
> +_LICENSE = "Creative Commons Attribution 4.0 (cc-by-4.0)"  # example: Licenses.MIT.value, Licenses.CC_BY_NC_SA_4_0.value, Licenses.UNLICENSE.value, Licenses.UNKNOWN.value
Please remove the `# example` comments (also in `_SUPPORTED_TASKS`), 

```suggestion
_LICENSE = "Creative Commons Attribution 4.0 (cc-by-4.0)" 
```

2024-02-14 20:39 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/malindo_parallel/malindo_parallel.py
> +class MalindoParallel(datasets.GeneratorBasedBuilder):
```suggestion
class MalindoParallelDataset(datasets.GeneratorBasedBuilder):
```

2024-03-03 09:35 UTC, bryanwilie commented
Sorry for the very late reply. Suggestions are committed, thank you for the feedback!

2024-03-04 01:04 UTC, ljvmiranda921 commented
LGTM! Let's just wait for @holylovenia 's review :)

2024-03-04 08:20 UTC, holylovenia requested changes
Hi @bryanwilie, thank you for the dataloader! It generally works well, but I find that it returns erroneous data instances for these exact IDs:

```
Train 59
{'id': '59',
 'text_1': 'Selain itu, pada peringkat penghujung tahun satu, hampir semua '
           'pelajar mengikuti Program Kembara Ilmu Inap Desa selama tiga '
           'minggu di Malaysia dan Singapura.',
 'text_1_name': 'zlm',
 'text_2': '',
 'text_2_name': 'jpn'}

Train 60
{'id': '60',
 'text_1': 'また、1年次の終わりにはほとんどの学生がマレーシア・シンガポールでの3週間のホームステイ・プログラムに参加します',
 'text_1_name': 'zlm',
 'text_2': 'また、1年次の終わりにはほとんどの学生がマレーシア・シンガポールでの3週間のホームステイ・プログラムに参加します',
 'text_2_name': 'jpn'}
```

This is due to [the original data instance ID 8-4 is split into 2 lines](https://github.com/matbahasa/MALINDO_Parallel/blob/0881bd2a9d0cd28e65a46c81e1605acdf1c95530/OpenCampusTUFS/OCTUFS2020.txt#L60) rather than the usual 1 line.

Additionally, could you please modify the `id` values to follow the IDs of the original data, e.g., `8-4`, `9-1`, etc.?

2024-03-18 05:04 UTC, holylovenia commented
Hi @bryanwilie, please let us know if you need any help for this PR! 👍

2024-03-25 02:50 UTC, holylovenia commented
Hi @bryanwilie, please let us know if you need any help for this PR! 👍

2024-04-01 07:02 UTC, bryanwilie commented
should be done!

2024-04-01 07:39 UTC, holylovenia approved these changes
LGTM!! Thanks a lot for your help, @bryanwilie!!

2024-04-01 07:39 UTC, merged