Add dataloader for Indonesia chinese mt robust eval
SEACrowd/seacrowd-datahub pull request #388
Opened 2024-01-28 07:39 UTC by TysonYu

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-02-25 06:36 UTC, jen-santoso requested changes
Hello @TysonYu 
Thank you for the dataloader implementation.
The dataloader runs well, however, there are some nits to fix as commented.

2024-03-03 08:36 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +    datasets.load_dataset(__file__)
Done

2024-03-03 08:37 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +_DATASETNAME = "[indonesia_chinese_mtrobusteval]"
Done

2024-03-03 08:38 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +# TODO: Add languages related to this dataset
Done, removed this line

2024-03-03 08:39 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +"""
Done

2024-03-03 08:40 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +    # method parameters are unpacked from `gen_kwargs` as given in `_split_generators`
Done

2024-03-03 08:41 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +class NewDataset(datasets.GeneratorBasedBuilder):
Done

2024-03-03 08:43 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +            name="indonesia_chinese_mtrobusteval_source",
done

2024-03-03 08:44 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +            subset_id="indonesia_chinese_mtrobusteval",
done

2024-03-03 08:44 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +            name="indonesia_chinese_mtrobusteval_seacrowd_t2t",
done

2024-03-03 08:44 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +            subset_id="indonesia_chinese_mtrobusteval",
done

2024-03-03 08:45 UTC, TysonYu commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +    DEFAULT_CONFIG_NAME = "indonesia_chinese_mtrobusteval_source"
done

2024-03-03 08:51 UTC, jen-santoso commented
@TysonYu 
Also, could you upload `__init__.py` as well?

2024-03-09 12:10 UTC, TysonYu commented
> @TysonYu Also, could you upload `__init__.py` as well?

Sure. Done~

2024-03-09 12:27 UTC, jen-santoso commented on seacrowd/sea_datasets/indonesia_chinese_mtrobusteval/indonesia_chinese_mtrobusteval.py
> +# https://github.com/huggingface/datasets/blob/master/templates/new_dataset_script.py
```suggestion
```

2024-03-09 12:28 UTC, jen-santoso commented
@TysonYu Thank you for the updates! now it's LGTM. Merging...

2024-03-09 12:29 UTC, merged