Closes #49 | Updated existing TICO_19 dataloader to support more sea languages
SEACrowd/seacrowd-datahub pull request #414
Opened 2024-02-05 09:54 UTC by ssun32

Closes #49 

### Checkbox
- [ ] Confirm that this PR is linked to the dataset issue.
- [ ] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [ ] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [ ] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [ ] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [ ] Confirm dataloader script works with `datasets.load_dataset` function.
- [ ] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-03-13 07:14 UTC, jen-santoso requested changes
One small nit. Other than that, tested and LGTM.

2024-03-14 06:09 UTC, ssun32 commented on seacrowd/sea_datasets/tico_19/tico_19.py
>  _LANGUAGES = ["ind", "ara", "spa", "fra", "hin", "por", "rus", "zho", "eng"]
hello @jen-santoso, added the SEA languages.

2024-03-16 16:02 UTC, jen-santoso approved these changes

2024-03-16 16:02 UTC, jen-santoso commented
@ssun32 , thank you for the updates! Merging now

2024-03-16 16:03 UTC, merged