Create indonesian_news_dataset dataloader
SEACrowd/seacrowd-datahub pull request #433
Opened 2024-02-14 07:55 UTC by joanitolopo

Closes #422

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-03-09 09:53 UTC, SamuelCahyawijaya approved these changes
Hi @joanitolopo, thank you for the contribution! LGTM!

2024-03-11 03:53 UTC, raileymontalan requested changes

2024-03-11 03:53 UTC, raileymontalan commented on seacrowd/sea_datasets/indonesian_news_dataset/indonesian_news_dataset.py
> +The dataset comprises of around 6k train and 2.5k test examples, with the more prevalent classes
Please remove the trailing white spaces here. 
Run make check_file=seacrowd/sea_datasets/malaysia_tweets/malaysia_tweets.py to check the necessary changes to your script.

2024-03-19 16:19 UTC, raileymontalan approved these changes
LGTM. Thanks!

2024-03-19 16:20 UTC, merged