Flores200
SEACrowd/seacrowd-datahub pull request #456
Opened 2024-02-24 20:37 UTC by Enliven26

Closes [#46](https://github.com/SEACrowd/seacrowd-datahub/issues/46)

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-02-26 12:12 UTC, holylovenia requested changes
Hi @Enliven26, thanks for your contribution. I happened to pass by this dataloader and added some comments:

2024-02-26 12:12 UTC, holylovenia commented on seacrowd/sea_datasets/flores200/flores200.py
> +                subset_id = f"{first_lang}_{second_lang}_{script_names}"
Hi @Enliven26, may I know why you didn't use `subset_id = f"{first_lang_name}_{second_lang_name}"`?

2024-02-26 12:12 UTC, holylovenia commented on seacrowd/sea_datasets/flores200/flores200.py
> +                        name=f"{subset_id}_source",
Please prepend the `{_DATASETNAME}`.

2024-02-26 12:12 UTC, holylovenia commented on seacrowd/sea_datasets/flores200/flores200.py
> +                            name=f"{subset_id}_{seacrowd_schema}",
Please prepend the `{_DATASETNAME}`.

2024-02-26 12:12 UTC, holylovenia commented on seacrowd/sea_datasets/flores200/flores200.py
> +    DEFAULT_CONFIG_NAME = f"{_LANGUAGES[0]}{_LANGUAGES[1]}_{_SCRIPT_LANGUAGE_NAMES[0]}_source"
Please prepend the `{_DATASETNAME}`.

2024-03-02 07:06 UTC, SamuelCahyawijaya requested changes
Hi @Enliven26 , thank you for the contribution! I think in the current scenario, you only take the language pairs with` Eng_Latn` as the source language. 

For MT datasets, we take all language pairs where at least one of the language is in the `_LANGUAGES` list. Could you be able to update it accordingly.

2024-03-02 07:06 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/flores200/flores200.py
> +        BUILDER_CONFIGS.extend(seacrowd_schema_config)
We need to take all the language pairs where one of the language is in the `_LANGUAGES` list

2024-03-02 07:06 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/flores200/flores200.py
> +# This allows you to run your dataloader with `python [dataset_name].py` during development
I think we can remove this part in the PR

2024-03-02 07:10 UTC, SamuelCahyawijaya commented
Ups @Enliven26, sorry for the last comment, I think we have a conflicting argument here. Let me discuss this internally first with @holylovenia  and the others regarding which subsets should we take 🙏🏻

2024-03-05 09:31 UTC, holylovenia commented
> Ups @Enliven26, sorry for the last comment, I think we have a conflicting argument here. Let me discuss this internally first with @holylovenia and the others regarding which subsets should we take 🙏🏻

Hi @Enliven26, apologies for the previous contradictory advice. 🙏 After discussing, this is what we agreed on.

For parallel MT dataloaders, we agreed upon having a subset for every possible direction with at least 1 SEA language.

For example, if the parallel MT dataloader has these languages: ind, sun, eng, spa, fil, mya, the dataloader consists of these subsets:
- `_{DATALOADERNAME}_eng_ind_seacrowd_t2t`
- `_{DATALOADERNAME}_eng_sun_seacrowd_t2t`
- `_{DATALOADERNAME}_eng_mya_seacrowd_t2t`
- `_{DATALOADERNAME}_ind_eng_seacrowd_t2t`
- `_{DATALOADERNAME}_sun_eng_seacrowd_t2t`
- `_{DATALOADERNAME}_mya_eng_seacrowd_t2t`
- `_{DATALOADERNAME}_spa_ind_seacrowd_t2t`
- `_{DATALOADERNAME}_spa_sun_seacrowd_t2t`
- `_{DATALOADERNAME}_spa_mya_seacrowd_t2t`
- `_{DATALOADERNAME}_ind_spa_seacrowd_t2t`
- `_{DATALOADERNAME}_sun_spa_seacrowd_t2t`
- `_{DATALOADERNAME}_mya_spa_seacrowd_t2t`
- `_{DATALOADERNAME}_ind_sun_seacrowd_t2t`
- `_{DATALOADERNAME}_ind_mya_seacrowd_t2t`
- `_{DATALOADERNAME}_sun_ind_seacrowd_t2t`
- `_{DATALOADERNAME}_mya_ind_seacrowd_t2t`
- `_{DATALOADERNAME}_sun_mya_seacrowd_t2t`
- `_{DATALOADERNAME}_mya_sun_seacrowd_t2t`

But since `eng` and `spa` are both non-SEA languages, no need to include `_{DATALOADERNAME}_eng_spa_seacrowd_t2t` and `_{DATALOADERNAME}_spa_eng_seacrowd_t2t`.

cc: @SamuelCahyawijaya @sabilmakbar

2024-03-05 15:17 UTC, Enliven26 commented
> > Ups @Enliven26, sorry for the last comment, I think we have a conflicting argument here. Let me discuss this internally first with @holylovenia and the others regarding which subsets should we take 🙏🏻
> 
> Hi @Enliven26, apologies for the previous contradictory advice. 🙏 After discussing, this is what we agreed on.
> 
> For parallel MT dataloaders, we agreed upon having a subset for every possible direction with at least 1 SEA language.
> 
> For example, if the parallel MT dataloader has these languages: ind, sun, eng, spa, fil, mya, the dataloader consists of these subsets:
> 
> * `_{DATALOADERNAME}_eng_ind_seacrowd_t2t`
> * `_{DATALOADERNAME}_eng_sun_seacrowd_t2t`
> * `_{DATALOADERNAME}_eng_mya_seacrowd_t2t`
> * `_{DATALOADERNAME}_ind_eng_seacrowd_t2t`
> * `_{DATALOADERNAME}_sun_eng_seacrowd_t2t`
> * `_{DATALOADERNAME}_mya_eng_seacrowd_t2t`
> * `_{DATALOADERNAME}_spa_ind_seacrowd_t2t`
> * `_{DATALOADERNAME}_spa_sun_seacrowd_t2t`
> * `_{DATALOADERNAME}_spa_mya_seacrowd_t2t`
> * `_{DATALOADERNAME}_ind_spa_seacrowd_t2t`
> * `_{DATALOADERNAME}_sun_spa_seacrowd_t2t`
> * `_{DATALOADERNAME}_mya_spa_seacrowd_t2t`
> * `_{DATALOADERNAME}_ind_sun_seacrowd_t2t`
> * `_{DATALOADERNAME}_ind_mya_seacrowd_t2t`
> * `_{DATALOADERNAME}_sun_ind_seacrowd_t2t`
> * `_{DATALOADERNAME}_mya_ind_seacrowd_t2t`
> * `_{DATALOADERNAME}_sun_mya_seacrowd_t2t`
> * `_{DATALOADERNAME}_mya_sun_seacrowd_t2t`
> 
> But since `eng` and `spa` are both non-SEA languages, no need to include `_{DATALOADERNAME}_eng_spa_seacrowd_t2t` and `_{DATALOADERNAME}_spa_eng_seacrowd_t2t`.
> 
> cc: @SamuelCahyawijaya @sabilmakbar

given `_{DATALOADERNAME}_eng_ind_seacrowd_t2t` as example, should I include the transcript language for the subset so that it becomes `_{DATALOADERNAME}_eng_Latn_ind_Arab_seacrowd_t2t` for example? If not, then what is the default transcript language for both text?

2024-03-07 06:45 UTC, holylovenia commented
> given `_{DATALOADERNAME}_eng_ind_seacrowd_t2t` as example, should I include the transcript language for the subset so that it becomes `_{DATALOADERNAME}_eng_Latn_ind_Arab_seacrowd_t2t` for example? If not, then what is the default transcript language for both text?

Yes yes, please use the transcript as you described as well. 🙏 Thank you so much, @Enliven26!!

2024-03-07 11:38 UTC, Enliven26 commented
Hi, please review my recent commit. Thanks!

2024-03-09 09:32 UTC, SamuelCahyawijaya requested changes
Hi @Enliven26, thank you for updating the code!

It seems like there are two problems, one with the subset naming and the other one with the loaded dataset.

I have put some comments on the code, please update them accordingly and let me know if there is any problem.

2024-03-09 09:32 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/flores200/flores200.py
> +            subset_id = f"{_DATASETNAME}_{first_lang_name}_{second_lang_name}_seacrowd_t2t"
The current subset name looks like: `flores200_*_seacrowd_t2t_seacrowd_t2t` and ` 'flores200_*_seacrowd_t2t_source`, we can remove the `_seacrowd_t2t` here to fix the problem

2024-03-09 09:32 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/flores200/flores200.py
> +        for path, lang in zip(sentence_paths, langs):
The `sentence_path` provides the paths to the data for all available languages in Flores, while the `langs` is only lang1 and lang2, this causes misalignment between the data and the language code as shown below:

zsm_Latn - ind_Latn
```
>>> x = datasets.load_dataset('seacrowd/sea_datasets/flores200/flores200.py', name='flores200_zsm_Latn_ind_Latn_seacrowd_t2t_seacrowd_t2t')
>>> x['dev'][0]
{'id': '1', 'text_1': 'يق أورو سنين، اوق علمون دري فکولتس کدوکترن يونيۏرسيتس ستانفورد ݢڤعموم اکن جتومى الت دياݢنوستيک بارو ڽڠ جوت ݢڤيليه اتو سيل منوروت جنيهجيه: چيڤ اوبيت ڽڠ جوت ݢچيتق ڽڠ جوت ݢڤݢت دڠون ڤرينتر ايڠ\u200cکجيت ستندر دڠون يوم موڠکين نا سابوه سين ا.س. لم تيڤ سابوه.', 'text_2': 'Bak uroe Senin, awak ilmuwan dari Fakultas Kedokteran Universitas Stanford geu peuumum akan jiteumèe alat diagnostik baro nyang jeuet geupileh atoe sel meunurot jeunèhjih: chip ubit nyang jeuet geucetak nyang jeuet geupeuget deungôn printer inkjèt standar deungôn yum mungken na sabôh sen AS lam tiep sabôh.', 'text_1_name': 'zsm_Latn', 'text_2_name': 'ind_Latn'}
```

eng_Latn - ind_Latn
```
>>> x = datasets.load_dataset('seacrowd/sea_datasets/flores200/flores200.py', name='flores200_eng_Latn_ind_Latn_seacrowd_t2t_seacrowd_t2t')
>>> x['dev'][0]
{'id': '1', 'text_1': 'يق أورو سنين، اوق علمون دري فکولتس کدوکترن يونيۏرسيتس ستانفورد ݢڤعموم اکن جتومى الت دياݢنوستيک بارو ڽڠ جوت ݢڤيليه اتو سيل منوروت جنيهجيه: چيڤ اوبيت ڽڠ جوت ݢچيتق ڽڠ جوت ݢڤݢت دڠون ڤرينتر ايڠ\u200cکجيت ستندر دڠون يوم موڠکين نا سابوه سين ا.س. لم تيڤ سابوه.', 'text_2': 'Bak uroe Senin, awak ilmuwan dari Fakultas Kedokteran Universitas Stanford geu peuumum akan jiteumèe alat diagnostik baro nyang jeuet geupileh atoe sel meunurot jeunèhjih: chip ubit nyang jeuet geucetak nyang jeuet geupeuget deungôn printer inkjèt standar deungôn yum mungken na sabôh sen AS lam tiep sabôh.', 'text_1_name': 'eng_Latn', 'text_2_name': 'ind_Latn'}
```

2024-03-11 05:37 UTC, Enliven26 commented
Hi @SamuelCahyawijaya , sorry for the misaligment error. I already fixed it, please review the changes. Thanks!

2024-03-11 05:56 UTC, holylovenia approved these changes
LGTM! Thanks a lot, @Enliven26!

2024-03-15 05:21 UTC, SamuelCahyawijaya approved these changes
@Enliven26 : Thank you for the updates! LGTM!

2024-03-15 05:21 UTC, merged