Closes #222 | Create dataset loader for CreoleRC
SEACrowd/seacrowd-datahub pull request #469
Opened 2024-03-01 12:22 UTC by zwenyu

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-03-14 06:54 UTC, faridlazuarda approved these changes
I have manually tested all the functionality and subset (including the relations structuring) and this looks good to me! Thank you for the contribution, @zwenyu.

2024-03-14 12:30 UTC, sabilmakbar commented
Hi @zwenyu, to make the reviewing tidier, would you like to separate config changes into a different PR? (so you can be attributed for bonus points in introducing new tasks, too)

2024-03-14 17:22 UTC, zwenyu commented
@sabilmakbar I've removed the config changes in constant.py to a separate PR #502.

2024-03-17 06:02 UTC, sabilmakbar requested changes

2024-03-17 06:02 UTC, sabilmakbar commented on seacrowd/sea_datasets/creole_rc/creole_rc.py
> +                }
missing `normalized` on this schema that leads to error on my end. Not sure why @faridlazuarda's test works on his end, prob due to earlier version of `datasets` module, tho. mine tested on `datasets==2.16.1`

2024-03-17 06:02 UTC, sabilmakbar commented on seacrowd/sea_datasets/creole_rc/creole_rc.py
> +                offset_entity2 = csv_data[i][0].find(csv_data[i][2])
Can we put a sanity check if either of these values isn't found, leading to a -1 value? we can skip those rows if that's the case

2024-03-17 12:24 UTC, zwenyu commented
@sabilmakbar Thanks for the comments. I've pushed changes addressing the issues. Can you check if they are ok?

2024-03-17 14:51 UTC, sabilmakbar commented
> @sabilmakbar Thanks for the comments. I've pushed changes addressing the issues. I didn't see error for normalized, using datasets version 2.17.1, but I've added normalized now. Can you check if they are ok?

Initially, I pointed to the missing field of `normalized` in the SEACrowd Schema of KB under the `relations` column, which is okay if being filled with an empty list. But since your new changes also fill them with appropriate values, it works (and even better)!

2024-03-17 14:51 UTC, sabilmakbar approved these changes
LGTM! Thanks a lot, @zwenyu and @faridlazuarda!

2024-03-17 14:51 UTC, merged