Closes #437 | Create lex_indo dataset loader
SEACrowd/seacrowd-datahub pull request #539
Opened 2024-03-19 06:57 UTC by joanitolopo

Closes #437 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

![image](https://github.com/SEACrowd/seacrowd-datahub/assets/68073738/04faafac-d563-463e-82e5-196c87f10403)

2024-04-13 17:31 UTC, patrickamadeus requested changes
Hi @joanitolopo! Thank you for the PR for `lex_indo` dataloader. 

Everything besides requested changes is good! Tested locally and satisfy all cases. 

I would say this case can be implemented with the available `seacrowd` schema, which is `t2t` for Lexical Normalization as mentioned in issue card.

2024-04-13 17:31 UTC, patrickamadeus commented on seacrowd/sea_datasets/lex_indo/lex_indo.py
> +_SUPPORTED_TASKS = []
Hi @joanitolopo ! Could you please add the corresponding task from the issue? 

I believe it should be
```suggestion
_SUPPORTED_TASKS = [Tasks.MULTILEXNORM]
```

2024-04-13 17:31 UTC, patrickamadeus commented on seacrowd/sea_datasets/lex_indo/lex_indo.py
> +    ]
There should be `seacrowd` schema instead of only `source`, especially since `Tasks.MULTILEXNORM` has been supported by `T2T` schema.

2024-04-13 17:31 UTC, patrickamadeus commented on seacrowd/sea_datasets/lex_indo/lex_indo.py
> +
Please include the supported `_LANGUAGES`, which is `ind`.
```suggestion
_LANGUAGES = ['ind']
```

2024-04-13 17:31 UTC, patrickamadeus commented on seacrowd/sea_datasets/lex_indo/lex_indo.py
> +            raise NotImplementedError()
```suggestion
           features = schemas.text2text_features
```

2024-04-13 17:31 UTC, patrickamadeus commented on seacrowd/sea_datasets/lex_indo/lex_indo.py
> +            raise ValueError(f"Invalid config: {self.config.name}")
Please also implement the normalized phoneme for `seacrowd_t2t` schema

2024-04-22 10:23 UTC, faridlazuarda approved these changes
Everything works well on my side, addressing Patrick's comment would be sufficient. LGTM!

2024-05-07 15:39 UTC, joanitolopo commented
Halo @holylovenia and @patrickamadeus 👋
I've made changes and addressed all suggestions. 
Thankyou

2024-05-13 07:35 UTC, patrickamadeus approved these changes
LGTM! Thanks for addressing the request and sorry for the late response ☺️

2024-05-13 07:43 UTC, merged