Closes #523 | Add/Update Dataloader PFSA-ID
SEACrowd/seacrowd-datahub pull request #547
Opened 2024-03-22 15:27 UTC by patrickamadeus

Closes #523 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [.] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### pfsa_id
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/65403659/90179499-4392-4506-9654-803e13032ea3)

### pfsa_id_med
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/65403659/331fbd87-86ba-4c9f-bce0-35b001e59fdf)

### pfsa_id_test
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/65403659/fe3af838-4c98-4bfc-8722-37ab6da55845)

2024-04-08 09:24 UTC, SamuelCahyawijaya approved these changes
LGTM!

2024-04-09 00:55 UTC, MJonibek requested changes
@patrickamadeus Thank you for working on this dataloader. Your dataloader produces only three samples per split (which means one sample per file), however, inside the file, there are multiple sentences. I think you need to separate each sentence into a single sample, rather than unite them into one. 

What do you think @SamuelCahyawijaya?

2024-04-14 07:03 UTC, SamuelCahyawijaya requested changes
Hello @patrickamadeus @MJonibek, sorry, I missed this one before and thank you for noticing this one.

Yes, @MJonibek is correct, an instance for tagging task is commonly splitted per sentence in the conll format. So, it we should yield the instance when there is an empty row instead of just skipping the empty line.

2024-04-15 05:34 UTC, patrickamadeus commented on seacrowd/sea_datasets/pfsa_id/pfsa_id.py
> +                if line == "\n":
Thanks for the review @MJonibek @SamuelCahyawijaya ! Please check the latest commit for the revision, it should have been wrapped up!

2024-04-15 11:14 UTC, MJonibek approved these changes
@patrickamadeus Great work, LGTM. One small issue: please rerun make command and solve issues it shows (screen attached)

<img width="870" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/44943993/22719154-2b6e-4762-aca2-ac09f2ec80e0">

2024-04-20 02:10 UTC, SamuelCahyawijaya approved these changes
Thank you for the update, @patrickamadeus! LGTM!

2024-04-20 02:10 UTC, merged