Closes #514| Add/Update Dataloader CCMatrix
SEACrowd/seacrowd-datahub pull request #548
Opened 2024-03-22 18:17 UTC by patrickamadeus

Closes #514 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [.] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### jv-ms
<img width="990" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/65403659/bbb6d690-cf6b-437a-a8e5-d71d845ece7e">

### en-jv
<img width="678" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/65403659/2f4c1440-87f0-426a-899e-39f8d78cc223">

2 test samples out of 14 total pairs

2024-03-23 15:00 UTC, patrickamadeus commented
will add `ssp` schema within this week after discussing with @SamuelCahyawijaya

2024-04-14 07:23 UTC, SamuelCahyawijaya requested changes
@patrickamadeus, Thank you for the contribution. The dataset looks great, and I only have feedback regarding the language code standard. 

Could we change the one in the subset name so that it follows the same ISO 639-3 standard as in the `_LANGUAGES`?

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                name=f"{_DATASETNAME}_{lang1}-{lang2}_source",
For the lang code, can we change it so that it follows the same ISO 639-3 standard as in the `_LANGUAGES`?

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                description=f"{_DATASETNAME} source schema for translation from {lang1} to {lang2}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                subset_id=f"{_DATASETNAME}_{lang1}-{lang2}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                name=f"{_DATASETNAME}_{lang1}-{lang2}_{lang1}_source",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                description=f"{_DATASETNAME} source schema {lang1} for translation from {lang1} to {lang2}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                subset_id=f"{_DATASETNAME}_{lang1}-{lang2}_{lang1}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                name=f"{_DATASETNAME}_{lang1}-{lang2}_{lang2}_source",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                description=f"{_DATASETNAME} source schema {lang2} for translation from {lang1} to {lang2}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                subset_id=f"{_DATASETNAME}_{lang1}-{lang2}_{lang2}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                name=f"{_DATASETNAME}_{lang1}-{lang2}_seacrowd_t2t",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                subset_id=f"{_DATASETNAME}_{lang1}-{lang2}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                name=f"{_DATASETNAME}_{lang1}-{lang2}_{lang1}_seacrowd_ssp",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                description=f"{_DATASETNAME} SEACrowd schema {lang1} for translation from {lang1} to {lang2} for Self-supervised Pretraining task",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                subset_id=f"{_DATASETNAME}_{lang1}-{lang2}_{lang1}",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                name=f"{_DATASETNAME}_{lang1}-{lang2}_{lang2}_seacrowd_ssp",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                description=f"{_DATASETNAME} SEACrowd schema {lang2} for translation from {lang1} to {lang2} for Self-supervised Pretraining task",
Same as above

2024-04-14 07:23 UTC, SamuelCahyawijaya commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
> +                subset_id=f"{_DATASETNAME}_{lang1}-{lang2}_{lang2}",
Same as above

2024-04-20 02:29 UTC, SamuelCahyawijaya approved these changes
@patrickamadeus : thank you for the contribution! LGTM!

2024-05-14 07:58 UTC, muhammadravi251001 commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
LGTM. Great work @patrickamadeus. Merging in a second.

2024-05-14 08:00 UTC, muhammadravi251001 approved these changes

2024-05-14 08:00 UTC, muhammadravi251001 commented on seacrowd/sea_datasets/ccmatrix/ccmatrix.py
LGTM. Great work @patrickamadeus. Merging in a second.

2024-05-14 08:00 UTC, merged