Closes #12 | Add/Update Dataloader BalitaNLP
SEACrowd/seacrowd-datahub pull request #550
Opened 2024-03-27 03:59 UTC by raileymontalan

Closes #12

### Notes
There are many articles in the dataset whose corresponding image file does not exist in the repository. Reporting the statistics here:
- `train` split (281403 total examples): 18923 missing images (~6.72%)
- `test` split (35177 total examples): 2356 missing images (~6.70%)
- `validation` split (35175 total examples): 2369 missing images (~6.73%)

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-04-03 07:09 UTC, holylovenia requested changes
Hi @raileymontalan, looks good to me! I have one suggestion though.

Could you please add the `author`, `category`, `date`, `img_url`, `url`, and `website` under the `metadata` in the `seacrowd_imtext` schema?

2024-04-05 03:19 UTC, ljvmiranda921 approved these changes
LGTM! I think just address @holylovenia 's comment and we're good!

2024-04-08 05:38 UTC, raileymontalan commented
> Hi @raileymontalan, looks good to me! I have one suggestion though.
> 
> Could you please add the `author`, `category`, `date`, `img_url`, `url`, and `website` under the `metadata` in the `seacrowd_imtext` schema?

Details added to metadata. Ready for review, thanks!

2024-04-08 06:25 UTC, holylovenia approved these changes
Thank you for the changes, @raileymontalan!! LGTM. 😁 Merging now.

2024-04-08 06:25 UTC, merged