Closes #535 | Add Dataloader CulturaY
SEACrowd/seacrowd-datahub pull request #559
Opened 2024-03-30 22:47 UTC by akhdanfadh

Closes #535 

I implemented one config per language/subset. Thus, configs will look like this: `culturay_id_source`, `culturay_my_seacrowd_ssp`, etc. When testing, pass `culturay_<subset>` to the `--subset_id` parameter.

Due to the large dataset, it will take time to test.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-04-23 21:57 UTC, MJonibek reviewed
@akhdanfadh Hello, I am facing problem with this dataloader. I got permission from huggingface and passing my read token when loading dataloader, but still getting:

`Cannot access gated repo for URL https://huggingface.co/api/datasets/ontocord/CulturaY. Access to dataset ontocord/CulturaY is restricted and you are not in the authorized list. Visit https://huggingface.co/datasets/ontocord/CulturaY to ask for access.` 

Any ideas what needs to be done?

2024-04-24 13:28 UTC, khelli07 commented
Have you accept the acknowledgement or form in the https://huggingface.co/datasets/ontocord/CulturaY ? It seems to work on my end. It's just the subset are quite a few and need some time--and spaces! :( --to run.

2024-04-25 22:46 UTC, akhdanfadh commented
> Cannot access gated repo for URL https://huggingface.co/api/datasets/ontocord/CulturaY. Access to dataset ontocord/CulturaY is restricted and you are not in the authorized list. Visit https://huggingface.co/datasets/ontocord/CulturaY to ask for access.

Exactly as @khelli07 said, you need to accept the acknowledgment in the dataset repo. I already describe it in the description section of the dataloader actually.

> It's just the subset are quite a few and need some time--and spaces! :( --to run.

IKR, the dataset is huge. Not sure if there is something I can improve on this.

2024-04-29 21:50 UTC, MJonibek requested changes
@akhdanfadh @khelli07 Yes I got access to dataset, but I was getting error from above. I was running: 
`data = load_dataset('seacrowd/sea_datasets/culturay/culturay.py', token=auth_token, name='culturay_my_source')`

The problem was that token was not passed to `HfFileSystem`, with proposed changes it should work now

2024-04-29 21:50 UTC, MJonibek commented on seacrowd/sea_datasets/culturay/culturay.py
> +        file_list = HfFileSystem().ls(f"datasets/ontocord/CulturaY/{subset}", detail=False)
```suggestion
        fs = HfFileSystem(token=dl_manager.download_config.token)
        file_list = fs.ls(f"datasets/ontocord/CulturaY/{subset}", detail=False)
```

2024-05-07 08:11 UTC, holylovenia commented
A friendly reminder for @akhdanfadh to address @MJonibek and @khelli07's reviews.

2024-05-09 04:14 UTC, akhdanfadh commented
@MJonibek Done!
Also, please add your review or accept if LGTY @khelli07

2024-05-09 04:33 UTC, khelli07 approved these changes
LGTM!

2024-05-10 14:32 UTC, MJonibek approved these changes
@akhdanfadh Thank you for your work, LGTM!

2024-05-10 14:32 UTC, merged