Closes #527 | Add Dataloader MDIA
SEACrowd/seacrowd-datahub pull request #562
Opened 2024-03-31 11:04 UTC by akhdanfadh

Closes #527

I implemented one config per language/subset. Thus, configs will look like this: `mdia_ind_dialogue_source`, `mdia_tgl_eng_seacrowd_t2t`, etc. When testing, pass `mdia_<subset>` to the `--subset_id` parameter.

Note: this dataset can be used for two tasks and both use the same `t2t` schema with different implementation.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-04-09 01:12 UTC, MJonibek approved these changes
@akhdanfadh Checked, LGTM. Only one small issue: please run `make check_file=seacrowd/sea_datasets/mdia/mdia.py` to reformat file, and then resolve issues with formatting. 

<img width="879" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/44943993/5f000842-d0eb-422f-920d-6a3a71559d92">

2024-04-10 09:43 UTC, danjohnvelasco requested changes
LGTM. Please address the formatting issues as describe the other reviewer. I ran the formatter on my end and got similar output (see below). Other than this, no more issues. Thanks for your contribution 🫡

```
1 file reformatted.
isort seacrowd/sea_datasets/mdia/mdia.py
Fixing C:\Users\Dan\Documents\Research\seacrowd\seacrowd-datahub\seacrowd\sea_datasets\mdia\mdia.py
flake8 seacrowd/sea_datasets/mdia/mdia.py --max-line-length 250
seacrowd/sea_datasets/mdia/mdia.py:28:86: W291 trailing whitespace
seacrowd/sea_datasets/mdia/mdia.py:59:72: E262 inline comment should start with '# '
make: *** [Makefile:17: quality] Error 1
```

2024-04-18 09:32 UTC, akhdanfadh commented
@MJonibek @danjohnvelasco Done reformatting!

2024-05-07 08:13 UTC, holylovenia commented
I'm merging this since both @MJonibek and @danjohnvelasco's reviews have been addressed. Thank you so much for your work, @akhdanfadh!! 👍

2024-05-07 08:13 UTC, merged