Closes #616 | Add Dataloader TyDIQA-ID-NLI
SEACrowd/seacrowd-datahub pull request #632
Opened 2024-04-08 14:24 UTC by muhammadravi251001

**Title**: Add Dataloader TyDIQA-ID-NLI

**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/616

### Notes
- For the `_CITATION` field, I will add it later.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-04-29 20:37 UTC, MJonibek approved these changes
@muhammadravi251001 Checked, LGTM! Thank you for your work. Just small problem: can you delete unnecessary comment

2024-04-29 20:37 UTC, MJonibek commented on seacrowd/sea_datasets/tydiqa_id_nli/tydiqa_id_nli.py
> +# You can copy an official description
```suggestion

```

2024-04-29 22:33 UTC, muhammadravi251001 commented
> @muhammadravi251001 Checked, LGTM! Thank you for your work. Just small problem: can you delete unnecessary comment 

Thanks for the review, Sir!

2024-05-01 09:42 UTC, luckysusanto requested changes
The citation has not been added yet to the code.
Otherwise, this looks good!

2024-05-01 09:50 UTC, muhammadravi251001 commented
> The citation has not been added yet to the code. Otherwise, this looks good!

Yup, the citation is still not provided because I still waiting for the workshop's notification.

Thanks for the review, Lucky!

2024-05-07 08:38 UTC, holylovenia commented
Hi @luckysusanto, is there anything else that @muhammadravi251001 needs to address besides the pending `_CITATION`? I'd like to merge the dataloader if you don't find any other issues.

2024-05-11 13:14 UTC, luckysusanto commented
Sorry for the slow response @holylovenia 
No, I don't have more to add. I was thinking of waiting until the citation is put before accepting.
If it is not an issue, I'll approve now >.<.
Thanks!

2024-05-11 13:14 UTC, luckysusanto approved these changes

2024-05-13 06:14 UTC, merged