Closes #587 | Add/Update Dataloader MEN
SEACrowd/seacrowd-datahub pull request #634
Opened 2024-04-08 16:09 UTC by patrickamadeus

Closes #587 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [.] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### Test
<img width="1201" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/65403659/c575d529-1dfe-4a87-8c71-bf3cd3da052c">

2024-04-28 05:17 UTC, jen-santoso requested changes
Hi @patrickamadeus 
Thank you for implementing / updating the dataloader. 
Dataloader runs well, just a few nits in the comment.

2024-04-28 05:17 UTC, jen-santoso commented on seacrowd/sea_datasets/men/men.py
> +"""
Let's remove these lines, some are comments and some looks like a duplicate from `_DESCRIPTION`

2024-04-28 05:17 UTC, jen-santoso commented on seacrowd/sea_datasets/men/men.py
> +                        {"id": f"{article_id}-relation-{relation['id']}", "type": relation["relation"], "arg1_id": f"{article_id}-entity-{relation['head']}", "arg2_id": f"{article_id}-entity-{relatio
Please run the `make check_file` command. This line seems too long.

2024-04-30 07:08 UTC, patrickamadeus commented
Thank you for the revision @jen-santoso ! Could you kindly review the newest commit?

2024-05-13 14:55 UTC, jen-santoso approved these changes
Oops, sorry for the late reply. thanks for the reminder @holylovenia 
@patrickamadeus : LGTM! Thank you for implementing this dataloader and updating based on the comments! 
merging now

2024-05-13 14:55 UTC, merged