Closes #581 | Implement `vigetext` dataset
SEACrowd/seacrowd-datahub pull request #643
Opened 2024-04-14 16:26 UTC by chenxwh

Closes #581.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-04-23 22:19 UTC, MJonibek requested changes
@chenxwh Everything looks good, one small issue: you forgot to add `meta` key for seacrowd schema

2024-04-23 22:19 UTC, MJonibek commented on seacrowd/sea_datasets/vigetext/vigetext.py
> +                    "answer": [answer_map[item["target"]]],
```suggestion
                    "answer": [answer_map[item["target"]]],
                    "meta": {},
```

2024-04-29 20:04 UTC, MJonibek approved these changes
LGTM

2024-05-07 08:46 UTC, holylovenia commented
A friendly reminder for @akhdanfadh to review.

2024-05-09 04:58 UTC, akhdanfadh commented
LGTM! Thank you for the dataloader @chenxwh . Merging this in a bit.

2024-05-09 04:59 UTC, akhdanfadh approved these changes

2024-05-09 05:02 UTC, merged