Closes #591 | Add/Update medisco
SEACrowd/seacrowd-datahub pull request #654
Opened 2024-04-21 07:41 UTC by mrqorib

Closes #591

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

2024-05-12 02:22 UTC, ljvmiranda921 approved these changes
LGTM!

2024-05-12 02:22 UTC, ljvmiranda921 commented on seacrowd/sea_datasets/medisco/medisco.py
> +_UNIFIED_VIEW_NAME = DEFAULT_SEACROWD_VIEW_NAME
I think this is not required anymore? I might be wrong

```suggestion
```

2024-05-14 12:51 UTC, MJonibek requested changes
@mrqorib Thank you for your work. Please address changes from @ljvmiranda921 . Also please run `make` command for reformatting and address errors:

<img width="841" alt="image" src="https://github.com/SEACrowd/seacrowd-datahub/assets/44943993/d98adf78-72e7-4389-b35c-d4419c674e4e">

2024-05-15 11:21 UTC, mrqorib commented
Thank you @ljvmiranda921 and @MJonibek for the review! I apologize for missing the make file step

2024-05-15 15:14 UTC, MJonibek approved these changes
LGTM, great work @mrqorib

2024-05-15 15:14 UTC, merged